# Copyright 2025 The Marin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: cluster.proto

from collections.abc import AsyncGenerator, Iterable, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import cluster_pb2 as cluster__pb2


class ControllerService(Protocol):
    async def launch_job(
        self, request: cluster__pb2.LaunchJobRequest, ctx: RequestContext
    ) -> cluster__pb2.LaunchJobResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_job_status(
        self, request: cluster__pb2.GetJobStatusRequest, ctx: RequestContext
    ) -> cluster__pb2.GetJobStatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def terminate_job(self, request: cluster__pb2.TerminateJobRequest, ctx: RequestContext) -> cluster__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_jobs(
        self, request: cluster__pb2.ListJobsRequest, ctx: RequestContext
    ) -> cluster__pb2.ListJobsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def register_endpoint(
        self, request: cluster__pb2.RegisterEndpointRequest, ctx: RequestContext
    ) -> cluster__pb2.RegisterEndpointResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def unregister_endpoint(
        self, request: cluster__pb2.UnregisterEndpointRequest, ctx: RequestContext
    ) -> cluster__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def lookup_endpoint(
        self, request: cluster__pb2.LookupEndpointRequest, ctx: RequestContext
    ) -> cluster__pb2.LookupEndpointResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_endpoints(
        self, request: cluster__pb2.ListEndpointsRequest, ctx: RequestContext
    ) -> cluster__pb2.ListEndpointsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ControllerServiceASGIApplication(ConnectASGIApplication[ControllerService]):
    def __init__(
        self,
        service: ControllerService | AsyncGenerator[ControllerService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/fluster.cluster.ControllerService/LaunchJob": Endpoint.unary(
                    method=MethodInfo(
                        name="LaunchJob",
                        service_name="fluster.cluster.ControllerService",
                        input=cluster__pb2.LaunchJobRequest,
                        output=cluster__pb2.LaunchJobResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.launch_job,
                ),
                "/fluster.cluster.ControllerService/GetJobStatus": Endpoint.unary(
                    method=MethodInfo(
                        name="GetJobStatus",
                        service_name="fluster.cluster.ControllerService",
                        input=cluster__pb2.GetJobStatusRequest,
                        output=cluster__pb2.GetJobStatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_job_status,
                ),
                "/fluster.cluster.ControllerService/TerminateJob": Endpoint.unary(
                    method=MethodInfo(
                        name="TerminateJob",
                        service_name="fluster.cluster.ControllerService",
                        input=cluster__pb2.TerminateJobRequest,
                        output=cluster__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.terminate_job,
                ),
                "/fluster.cluster.ControllerService/ListJobs": Endpoint.unary(
                    method=MethodInfo(
                        name="ListJobs",
                        service_name="fluster.cluster.ControllerService",
                        input=cluster__pb2.ListJobsRequest,
                        output=cluster__pb2.ListJobsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_jobs,
                ),
                "/fluster.cluster.ControllerService/RegisterEndpoint": Endpoint.unary(
                    method=MethodInfo(
                        name="RegisterEndpoint",
                        service_name="fluster.cluster.ControllerService",
                        input=cluster__pb2.RegisterEndpointRequest,
                        output=cluster__pb2.RegisterEndpointResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.register_endpoint,
                ),
                "/fluster.cluster.ControllerService/UnregisterEndpoint": Endpoint.unary(
                    method=MethodInfo(
                        name="UnregisterEndpoint",
                        service_name="fluster.cluster.ControllerService",
                        input=cluster__pb2.UnregisterEndpointRequest,
                        output=cluster__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.unregister_endpoint,
                ),
                "/fluster.cluster.ControllerService/LookupEndpoint": Endpoint.unary(
                    method=MethodInfo(
                        name="LookupEndpoint",
                        service_name="fluster.cluster.ControllerService",
                        input=cluster__pb2.LookupEndpointRequest,
                        output=cluster__pb2.LookupEndpointResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.lookup_endpoint,
                ),
                "/fluster.cluster.ControllerService/ListEndpoints": Endpoint.unary(
                    method=MethodInfo(
                        name="ListEndpoints",
                        service_name="fluster.cluster.ControllerService",
                        input=cluster__pb2.ListEndpointsRequest,
                        output=cluster__pb2.ListEndpointsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_endpoints,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/fluster.cluster.ControllerService"


class ControllerServiceClient(ConnectClient):
    async def launch_job(
        self,
        request: cluster__pb2.LaunchJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.LaunchJobResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="LaunchJob",
                service_name="fluster.cluster.ControllerService",
                input=cluster__pb2.LaunchJobRequest,
                output=cluster__pb2.LaunchJobResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_job_status(
        self,
        request: cluster__pb2.GetJobStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.GetJobStatusResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetJobStatus",
                service_name="fluster.cluster.ControllerService",
                input=cluster__pb2.GetJobStatusRequest,
                output=cluster__pb2.GetJobStatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def terminate_job(
        self,
        request: cluster__pb2.TerminateJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="TerminateJob",
                service_name="fluster.cluster.ControllerService",
                input=cluster__pb2.TerminateJobRequest,
                output=cluster__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_jobs(
        self,
        request: cluster__pb2.ListJobsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.ListJobsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListJobs",
                service_name="fluster.cluster.ControllerService",
                input=cluster__pb2.ListJobsRequest,
                output=cluster__pb2.ListJobsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def register_endpoint(
        self,
        request: cluster__pb2.RegisterEndpointRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.RegisterEndpointResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RegisterEndpoint",
                service_name="fluster.cluster.ControllerService",
                input=cluster__pb2.RegisterEndpointRequest,
                output=cluster__pb2.RegisterEndpointResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def unregister_endpoint(
        self,
        request: cluster__pb2.UnregisterEndpointRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UnregisterEndpoint",
                service_name="fluster.cluster.ControllerService",
                input=cluster__pb2.UnregisterEndpointRequest,
                output=cluster__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def lookup_endpoint(
        self,
        request: cluster__pb2.LookupEndpointRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.LookupEndpointResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="LookupEndpoint",
                service_name="fluster.cluster.ControllerService",
                input=cluster__pb2.LookupEndpointRequest,
                output=cluster__pb2.LookupEndpointResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_endpoints(
        self,
        request: cluster__pb2.ListEndpointsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.ListEndpointsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListEndpoints",
                service_name="fluster.cluster.ControllerService",
                input=cluster__pb2.ListEndpointsRequest,
                output=cluster__pb2.ListEndpointsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class WorkerService(Protocol):
    async def run_job(self, request: cluster__pb2.RunJobRequest, ctx: RequestContext) -> cluster__pb2.RunJobResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_job_status(
        self, request: cluster__pb2.GetStatusRequest, ctx: RequestContext
    ) -> cluster__pb2.JobStatus:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_jobs(
        self, request: cluster__pb2.ListJobsRequest, ctx: RequestContext
    ) -> cluster__pb2.ListJobsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def fetch_logs(
        self, request: cluster__pb2.FetchLogsRequest, ctx: RequestContext
    ) -> cluster__pb2.FetchLogsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def kill_job(self, request: cluster__pb2.KillJobRequest, ctx: RequestContext) -> cluster__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def health_check(self, request: cluster__pb2.Empty, ctx: RequestContext) -> cluster__pb2.HealthResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class WorkerServiceASGIApplication(ConnectASGIApplication[WorkerService]):
    def __init__(
        self,
        service: WorkerService | AsyncGenerator[WorkerService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/fluster.cluster.WorkerService/RunJob": Endpoint.unary(
                    method=MethodInfo(
                        name="RunJob",
                        service_name="fluster.cluster.WorkerService",
                        input=cluster__pb2.RunJobRequest,
                        output=cluster__pb2.RunJobResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.run_job,
                ),
                "/fluster.cluster.WorkerService/GetJobStatus": Endpoint.unary(
                    method=MethodInfo(
                        name="GetJobStatus",
                        service_name="fluster.cluster.WorkerService",
                        input=cluster__pb2.GetStatusRequest,
                        output=cluster__pb2.JobStatus,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_job_status,
                ),
                "/fluster.cluster.WorkerService/ListJobs": Endpoint.unary(
                    method=MethodInfo(
                        name="ListJobs",
                        service_name="fluster.cluster.WorkerService",
                        input=cluster__pb2.ListJobsRequest,
                        output=cluster__pb2.ListJobsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_jobs,
                ),
                "/fluster.cluster.WorkerService/FetchLogs": Endpoint.unary(
                    method=MethodInfo(
                        name="FetchLogs",
                        service_name="fluster.cluster.WorkerService",
                        input=cluster__pb2.FetchLogsRequest,
                        output=cluster__pb2.FetchLogsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.fetch_logs,
                ),
                "/fluster.cluster.WorkerService/KillJob": Endpoint.unary(
                    method=MethodInfo(
                        name="KillJob",
                        service_name="fluster.cluster.WorkerService",
                        input=cluster__pb2.KillJobRequest,
                        output=cluster__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.kill_job,
                ),
                "/fluster.cluster.WorkerService/HealthCheck": Endpoint.unary(
                    method=MethodInfo(
                        name="HealthCheck",
                        service_name="fluster.cluster.WorkerService",
                        input=cluster__pb2.Empty,
                        output=cluster__pb2.HealthResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.health_check,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/fluster.cluster.WorkerService"


class WorkerServiceClient(ConnectClient):
    async def run_job(
        self,
        request: cluster__pb2.RunJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.RunJobResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RunJob",
                service_name="fluster.cluster.WorkerService",
                input=cluster__pb2.RunJobRequest,
                output=cluster__pb2.RunJobResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_job_status(
        self,
        request: cluster__pb2.GetStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.JobStatus:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetJobStatus",
                service_name="fluster.cluster.WorkerService",
                input=cluster__pb2.GetStatusRequest,
                output=cluster__pb2.JobStatus,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_jobs(
        self,
        request: cluster__pb2.ListJobsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.ListJobsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListJobs",
                service_name="fluster.cluster.WorkerService",
                input=cluster__pb2.ListJobsRequest,
                output=cluster__pb2.ListJobsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def fetch_logs(
        self,
        request: cluster__pb2.FetchLogsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.FetchLogsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="FetchLogs",
                service_name="fluster.cluster.WorkerService",
                input=cluster__pb2.FetchLogsRequest,
                output=cluster__pb2.FetchLogsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def kill_job(
        self,
        request: cluster__pb2.KillJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="KillJob",
                service_name="fluster.cluster.WorkerService",
                input=cluster__pb2.KillJobRequest,
                output=cluster__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def health_check(
        self,
        request: cluster__pb2.Empty,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.HealthResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="HealthCheck",
                service_name="fluster.cluster.WorkerService",
                input=cluster__pb2.Empty,
                output=cluster__pb2.HealthResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class ControllerServiceSync(Protocol):
    def launch_job(self, request: cluster__pb2.LaunchJobRequest, ctx: RequestContext) -> cluster__pb2.LaunchJobResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def get_job_status(
        self, request: cluster__pb2.GetJobStatusRequest, ctx: RequestContext
    ) -> cluster__pb2.GetJobStatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def terminate_job(self, request: cluster__pb2.TerminateJobRequest, ctx: RequestContext) -> cluster__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def list_jobs(self, request: cluster__pb2.ListJobsRequest, ctx: RequestContext) -> cluster__pb2.ListJobsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def register_endpoint(
        self, request: cluster__pb2.RegisterEndpointRequest, ctx: RequestContext
    ) -> cluster__pb2.RegisterEndpointResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def unregister_endpoint(
        self, request: cluster__pb2.UnregisterEndpointRequest, ctx: RequestContext
    ) -> cluster__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def lookup_endpoint(
        self, request: cluster__pb2.LookupEndpointRequest, ctx: RequestContext
    ) -> cluster__pb2.LookupEndpointResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def list_endpoints(
        self, request: cluster__pb2.ListEndpointsRequest, ctx: RequestContext
    ) -> cluster__pb2.ListEndpointsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ControllerServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: ControllerServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/fluster.cluster.ControllerService/LaunchJob": EndpointSync.unary(
                    method=MethodInfo(
                        name="LaunchJob",
                        service_name="fluster.cluster.ControllerService",
                        input=cluster__pb2.LaunchJobRequest,
                        output=cluster__pb2.LaunchJobResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.launch_job,
                ),
                "/fluster.cluster.ControllerService/GetJobStatus": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetJobStatus",
                        service_name="fluster.cluster.ControllerService",
                        input=cluster__pb2.GetJobStatusRequest,
                        output=cluster__pb2.GetJobStatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_job_status,
                ),
                "/fluster.cluster.ControllerService/TerminateJob": EndpointSync.unary(
                    method=MethodInfo(
                        name="TerminateJob",
                        service_name="fluster.cluster.ControllerService",
                        input=cluster__pb2.TerminateJobRequest,
                        output=cluster__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.terminate_job,
                ),
                "/fluster.cluster.ControllerService/ListJobs": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListJobs",
                        service_name="fluster.cluster.ControllerService",
                        input=cluster__pb2.ListJobsRequest,
                        output=cluster__pb2.ListJobsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_jobs,
                ),
                "/fluster.cluster.ControllerService/RegisterEndpoint": EndpointSync.unary(
                    method=MethodInfo(
                        name="RegisterEndpoint",
                        service_name="fluster.cluster.ControllerService",
                        input=cluster__pb2.RegisterEndpointRequest,
                        output=cluster__pb2.RegisterEndpointResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.register_endpoint,
                ),
                "/fluster.cluster.ControllerService/UnregisterEndpoint": EndpointSync.unary(
                    method=MethodInfo(
                        name="UnregisterEndpoint",
                        service_name="fluster.cluster.ControllerService",
                        input=cluster__pb2.UnregisterEndpointRequest,
                        output=cluster__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.unregister_endpoint,
                ),
                "/fluster.cluster.ControllerService/LookupEndpoint": EndpointSync.unary(
                    method=MethodInfo(
                        name="LookupEndpoint",
                        service_name="fluster.cluster.ControllerService",
                        input=cluster__pb2.LookupEndpointRequest,
                        output=cluster__pb2.LookupEndpointResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.lookup_endpoint,
                ),
                "/fluster.cluster.ControllerService/ListEndpoints": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListEndpoints",
                        service_name="fluster.cluster.ControllerService",
                        input=cluster__pb2.ListEndpointsRequest,
                        output=cluster__pb2.ListEndpointsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_endpoints,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/fluster.cluster.ControllerService"


class ControllerServiceClientSync(ConnectClientSync):
    def launch_job(
        self,
        request: cluster__pb2.LaunchJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.LaunchJobResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="LaunchJob",
                service_name="fluster.cluster.ControllerService",
                input=cluster__pb2.LaunchJobRequest,
                output=cluster__pb2.LaunchJobResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_job_status(
        self,
        request: cluster__pb2.GetJobStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.GetJobStatusResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetJobStatus",
                service_name="fluster.cluster.ControllerService",
                input=cluster__pb2.GetJobStatusRequest,
                output=cluster__pb2.GetJobStatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def terminate_job(
        self,
        request: cluster__pb2.TerminateJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="TerminateJob",
                service_name="fluster.cluster.ControllerService",
                input=cluster__pb2.TerminateJobRequest,
                output=cluster__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_jobs(
        self,
        request: cluster__pb2.ListJobsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.ListJobsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListJobs",
                service_name="fluster.cluster.ControllerService",
                input=cluster__pb2.ListJobsRequest,
                output=cluster__pb2.ListJobsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def register_endpoint(
        self,
        request: cluster__pb2.RegisterEndpointRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.RegisterEndpointResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RegisterEndpoint",
                service_name="fluster.cluster.ControllerService",
                input=cluster__pb2.RegisterEndpointRequest,
                output=cluster__pb2.RegisterEndpointResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def unregister_endpoint(
        self,
        request: cluster__pb2.UnregisterEndpointRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UnregisterEndpoint",
                service_name="fluster.cluster.ControllerService",
                input=cluster__pb2.UnregisterEndpointRequest,
                output=cluster__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def lookup_endpoint(
        self,
        request: cluster__pb2.LookupEndpointRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.LookupEndpointResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="LookupEndpoint",
                service_name="fluster.cluster.ControllerService",
                input=cluster__pb2.LookupEndpointRequest,
                output=cluster__pb2.LookupEndpointResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_endpoints(
        self,
        request: cluster__pb2.ListEndpointsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.ListEndpointsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListEndpoints",
                service_name="fluster.cluster.ControllerService",
                input=cluster__pb2.ListEndpointsRequest,
                output=cluster__pb2.ListEndpointsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class WorkerServiceSync(Protocol):
    def run_job(self, request: cluster__pb2.RunJobRequest, ctx: RequestContext) -> cluster__pb2.RunJobResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def get_job_status(self, request: cluster__pb2.GetStatusRequest, ctx: RequestContext) -> cluster__pb2.JobStatus:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def list_jobs(self, request: cluster__pb2.ListJobsRequest, ctx: RequestContext) -> cluster__pb2.ListJobsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def fetch_logs(self, request: cluster__pb2.FetchLogsRequest, ctx: RequestContext) -> cluster__pb2.FetchLogsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def kill_job(self, request: cluster__pb2.KillJobRequest, ctx: RequestContext) -> cluster__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def health_check(self, request: cluster__pb2.Empty, ctx: RequestContext) -> cluster__pb2.HealthResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class WorkerServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self, service: WorkerServiceSync, interceptors: Iterable[InterceptorSync] = (), read_max_bytes: int | None = None
    ) -> None:
        super().__init__(
            endpoints={
                "/fluster.cluster.WorkerService/RunJob": EndpointSync.unary(
                    method=MethodInfo(
                        name="RunJob",
                        service_name="fluster.cluster.WorkerService",
                        input=cluster__pb2.RunJobRequest,
                        output=cluster__pb2.RunJobResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.run_job,
                ),
                "/fluster.cluster.WorkerService/GetJobStatus": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetJobStatus",
                        service_name="fluster.cluster.WorkerService",
                        input=cluster__pb2.GetStatusRequest,
                        output=cluster__pb2.JobStatus,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_job_status,
                ),
                "/fluster.cluster.WorkerService/ListJobs": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListJobs",
                        service_name="fluster.cluster.WorkerService",
                        input=cluster__pb2.ListJobsRequest,
                        output=cluster__pb2.ListJobsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_jobs,
                ),
                "/fluster.cluster.WorkerService/FetchLogs": EndpointSync.unary(
                    method=MethodInfo(
                        name="FetchLogs",
                        service_name="fluster.cluster.WorkerService",
                        input=cluster__pb2.FetchLogsRequest,
                        output=cluster__pb2.FetchLogsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.fetch_logs,
                ),
                "/fluster.cluster.WorkerService/KillJob": EndpointSync.unary(
                    method=MethodInfo(
                        name="KillJob",
                        service_name="fluster.cluster.WorkerService",
                        input=cluster__pb2.KillJobRequest,
                        output=cluster__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.kill_job,
                ),
                "/fluster.cluster.WorkerService/HealthCheck": EndpointSync.unary(
                    method=MethodInfo(
                        name="HealthCheck",
                        service_name="fluster.cluster.WorkerService",
                        input=cluster__pb2.Empty,
                        output=cluster__pb2.HealthResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.health_check,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/fluster.cluster.WorkerService"


class WorkerServiceClientSync(ConnectClientSync):
    def run_job(
        self,
        request: cluster__pb2.RunJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.RunJobResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RunJob",
                service_name="fluster.cluster.WorkerService",
                input=cluster__pb2.RunJobRequest,
                output=cluster__pb2.RunJobResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_job_status(
        self,
        request: cluster__pb2.GetStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.JobStatus:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetJobStatus",
                service_name="fluster.cluster.WorkerService",
                input=cluster__pb2.GetStatusRequest,
                output=cluster__pb2.JobStatus,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_jobs(
        self,
        request: cluster__pb2.ListJobsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.ListJobsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListJobs",
                service_name="fluster.cluster.WorkerService",
                input=cluster__pb2.ListJobsRequest,
                output=cluster__pb2.ListJobsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def fetch_logs(
        self,
        request: cluster__pb2.FetchLogsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.FetchLogsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="FetchLogs",
                service_name="fluster.cluster.WorkerService",
                input=cluster__pb2.FetchLogsRequest,
                output=cluster__pb2.FetchLogsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def kill_job(
        self,
        request: cluster__pb2.KillJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="KillJob",
                service_name="fluster.cluster.WorkerService",
                input=cluster__pb2.KillJobRequest,
                output=cluster__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def health_check(
        self,
        request: cluster__pb2.Empty,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cluster__pb2.HealthResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="HealthCheck",
                service_name="fluster.cluster.WorkerService",
                input=cluster__pb2.Empty,
                output=cluster__pb2.HealthResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
