# Copyright 2025 The Marin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: worker.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
from . import worker_pb2 as worker__pb2


class WorkerService(Protocol):
    async def run_job(self, request: worker__pb2.RunJobRequest, ctx: RequestContext) -> worker__pb2.RunJobResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_job_status(
        self, request: worker__pb2.GetStatusRequest, ctx: RequestContext
    ) -> worker__pb2.GetStatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def stream_logs(
        self, request: worker__pb2.StreamLogsRequest, ctx: RequestContext
    ) -> AsyncIterator[worker__pb2.LogEntry]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def kill_job(self, request: worker__pb2.KillJobRequest, ctx: RequestContext) -> worker__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def health_check(self, request: worker__pb2.Empty, ctx: RequestContext) -> worker__pb2.HealthResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class WorkerServiceASGIApplication(ConnectASGIApplication[WorkerService]):
    def __init__(
        self,
        service: WorkerService | AsyncGenerator[WorkerService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/fluster.cluster.worker.WorkerService/RunJob": Endpoint.unary(
                    method=MethodInfo(
                        name="RunJob",
                        service_name="fluster.cluster.worker.WorkerService",
                        input=worker__pb2.RunJobRequest,
                        output=worker__pb2.RunJobResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.run_job,
                ),
                "/fluster.cluster.worker.WorkerService/GetJobStatus": Endpoint.unary(
                    method=MethodInfo(
                        name="GetJobStatus",
                        service_name="fluster.cluster.worker.WorkerService",
                        input=worker__pb2.GetStatusRequest,
                        output=worker__pb2.GetStatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_job_status,
                ),
                "/fluster.cluster.worker.WorkerService/StreamLogs": Endpoint.server_stream(
                    method=MethodInfo(
                        name="StreamLogs",
                        service_name="fluster.cluster.worker.WorkerService",
                        input=worker__pb2.StreamLogsRequest,
                        output=worker__pb2.LogEntry,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.stream_logs,
                ),
                "/fluster.cluster.worker.WorkerService/KillJob": Endpoint.unary(
                    method=MethodInfo(
                        name="KillJob",
                        service_name="fluster.cluster.worker.WorkerService",
                        input=worker__pb2.KillJobRequest,
                        output=worker__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.kill_job,
                ),
                "/fluster.cluster.worker.WorkerService/HealthCheck": Endpoint.unary(
                    method=MethodInfo(
                        name="HealthCheck",
                        service_name="fluster.cluster.worker.WorkerService",
                        input=worker__pb2.Empty,
                        output=worker__pb2.HealthResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.health_check,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/fluster.cluster.worker.WorkerService"


class WorkerServiceClient(ConnectClient):
    async def run_job(
        self,
        request: worker__pb2.RunJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> worker__pb2.RunJobResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RunJob",
                service_name="fluster.cluster.worker.WorkerService",
                input=worker__pb2.RunJobRequest,
                output=worker__pb2.RunJobResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_job_status(
        self,
        request: worker__pb2.GetStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> worker__pb2.GetStatusResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetJobStatus",
                service_name="fluster.cluster.worker.WorkerService",
                input=worker__pb2.GetStatusRequest,
                output=worker__pb2.GetStatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def stream_logs(
        self,
        request: worker__pb2.StreamLogsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[worker__pb2.LogEntry]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="StreamLogs",
                service_name="fluster.cluster.worker.WorkerService",
                input=worker__pb2.StreamLogsRequest,
                output=worker__pb2.LogEntry,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def kill_job(
        self,
        request: worker__pb2.KillJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> worker__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="KillJob",
                service_name="fluster.cluster.worker.WorkerService",
                input=worker__pb2.KillJobRequest,
                output=worker__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def health_check(
        self,
        request: worker__pb2.Empty,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> worker__pb2.HealthResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="HealthCheck",
                service_name="fluster.cluster.worker.WorkerService",
                input=worker__pb2.Empty,
                output=worker__pb2.HealthResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class WorkerServiceSync(Protocol):
    def run_job(self, request: worker__pb2.RunJobRequest, ctx: RequestContext) -> worker__pb2.RunJobResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def get_job_status(
        self, request: worker__pb2.GetStatusRequest, ctx: RequestContext
    ) -> worker__pb2.GetStatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def stream_logs(self, request: worker__pb2.StreamLogsRequest, ctx: RequestContext) -> Iterator[worker__pb2.LogEntry]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def kill_job(self, request: worker__pb2.KillJobRequest, ctx: RequestContext) -> worker__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def health_check(self, request: worker__pb2.Empty, ctx: RequestContext) -> worker__pb2.HealthResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class WorkerServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self, service: WorkerServiceSync, interceptors: Iterable[InterceptorSync] = (), read_max_bytes: int | None = None
    ) -> None:
        super().__init__(
            endpoints={
                "/fluster.cluster.worker.WorkerService/RunJob": EndpointSync.unary(
                    method=MethodInfo(
                        name="RunJob",
                        service_name="fluster.cluster.worker.WorkerService",
                        input=worker__pb2.RunJobRequest,
                        output=worker__pb2.RunJobResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.run_job,
                ),
                "/fluster.cluster.worker.WorkerService/GetJobStatus": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetJobStatus",
                        service_name="fluster.cluster.worker.WorkerService",
                        input=worker__pb2.GetStatusRequest,
                        output=worker__pb2.GetStatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_job_status,
                ),
                "/fluster.cluster.worker.WorkerService/StreamLogs": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="StreamLogs",
                        service_name="fluster.cluster.worker.WorkerService",
                        input=worker__pb2.StreamLogsRequest,
                        output=worker__pb2.LogEntry,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.stream_logs,
                ),
                "/fluster.cluster.worker.WorkerService/KillJob": EndpointSync.unary(
                    method=MethodInfo(
                        name="KillJob",
                        service_name="fluster.cluster.worker.WorkerService",
                        input=worker__pb2.KillJobRequest,
                        output=worker__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.kill_job,
                ),
                "/fluster.cluster.worker.WorkerService/HealthCheck": EndpointSync.unary(
                    method=MethodInfo(
                        name="HealthCheck",
                        service_name="fluster.cluster.worker.WorkerService",
                        input=worker__pb2.Empty,
                        output=worker__pb2.HealthResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.health_check,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/fluster.cluster.worker.WorkerService"


class WorkerServiceClientSync(ConnectClientSync):
    def run_job(
        self,
        request: worker__pb2.RunJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> worker__pb2.RunJobResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RunJob",
                service_name="fluster.cluster.worker.WorkerService",
                input=worker__pb2.RunJobRequest,
                output=worker__pb2.RunJobResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_job_status(
        self,
        request: worker__pb2.GetStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> worker__pb2.GetStatusResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetJobStatus",
                service_name="fluster.cluster.worker.WorkerService",
                input=worker__pb2.GetStatusRequest,
                output=worker__pb2.GetStatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def stream_logs(
        self,
        request: worker__pb2.StreamLogsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[worker__pb2.LogEntry]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="StreamLogs",
                service_name="fluster.cluster.worker.WorkerService",
                input=worker__pb2.StreamLogsRequest,
                output=worker__pb2.LogEntry,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def kill_job(
        self,
        request: worker__pb2.KillJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> worker__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="KillJob",
                service_name="fluster.cluster.worker.WorkerService",
                input=worker__pb2.KillJobRequest,
                output=worker__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def health_check(
        self,
        request: worker__pb2.Empty,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> worker__pb2.HealthResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="HealthCheck",
                service_name="fluster.cluster.worker.WorkerService",
                input=worker__pb2.Empty,
                output=worker__pb2.HealthResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
