FROM rayproject/ray:nightly.240914.bb15a3-py311-cpu
ARG VLLM_VERSION=0.6.6.post1

# Install general dependencies
RUN sudo apt-get update && sudo apt-get install -y clang curl g++ vim libpython3.11 libpython3.11-dev docker.io cmake

# Setup gcsfuse
RUN sudo apt install lsb-release -y
RUN export GCSFUSE_REPO=gcsfuse-`lsb_release -c -s` && echo "deb https://packages.cloud.google.com/apt $GCSFUSE_REPO main" | sudo tee /etc/apt/sources.list.d/gcsfuse.list
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
RUN sudo apt-get update && sudo apt-get install fuse gcsfuse -y
RUN sudo mkdir /opt/gcsfuse_mount
RUN sudo chown -R $(whoami) /opt/gcsfuse_mount

# Install resiliparse build dependencies (requires libre2-dev>=2022-04-01)
RUN sudo apt-get install -y build-essential zlib1g-dev liblz4-dev libuchardet-dev libre2-dev
# Install lexbor from source, since the apt package for jammy is corrupted
RUN set && curl -Lf https://github.com/lexbor/lexbor/archive/refs/tags/v2.3.0.tar.gz > lexbor.tar.gz \
    && tar -xf lexbor.tar.gz \
    && (cd lexbor-* && mkdir build \
        && cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -DLEXBOR_BUILD_SHARED=ON \
            -DLEXBOR_BUILD_STATIC=OFF \
            -DLEXBOR_OPTIMIZATION_LEVEL=-O3 \
            -B build \
        && sudo cmake --build build -j$(nproc) --target install) \
    && rm -rf lexbor*

# install rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH=$HOME/.cargo/bin:$PATH

RUN sudo mkdir -p /opt/marin/
RUN sudo chown -R $(whoami) /opt/marin/
# Ray uses conda
ENV PATH=/home/ray/anaconda3/bin:/home/ray/anaconda3/bin:/home/ray/anaconda3/condabin:$PATH

# gcloud
RUN conda install conda-forge::google-cloud-sdk -y
RUN gcloud components install alpha

RUN conda install -c conda-forge ncurses -y

## Install Pytorch and VLLM
#RUN sudo apt update && sudo apt install unzip -y
#RUN sudo mkdir -p /opt/vllm
#RUN sudo chown -R $(whoami) /opt/vllm
#RUN cd /opt/vllm && curl -sLO "https://github.com/vllm-project/vllm/archive/refs/tags/v${VLLM_VERSION}.zip" && unzip v${VLLM_VERSION}.zip
#
#WORKDIR /opt/vllm/vllm-${VLLM_VERSION}
#RUN pip uninstall torch torch-xla -y
#RUN sudo apt-get install libopenblas-base libopenmpi-dev libomp-dev -y
#
## NOTE(chris): Instead of running pip install requirements-tpus.txt as instructed, there is some bug
## where the current torch_xla version in the requirements-tpus.txt is not compatible with the platform (installation fails),
## so we install the dependencies manually from the requirements-tpu.txt file.
## This has been fixed in the new version: https://github.com/vllm-project/vllm/issues/11811#issuecomment-2575583282
## So we should replace this to a simple pip install -r requirements-tpu.txt command when the new version is released.
#RUN pip install -r requirements-common.txt
#RUN pip install cmake>=3.26 ninja packaging setuptools-scm>=8 wheel jinja2
#RUN pip install --no-cache-dir torch_xla[tpu]@https://storage.googleapis.com/pytorch-xla-releases/wheels/tpuvm/torch_xla-2.6.0.dev20241126-cp311-cp311-linux_x86_64.whl -f https://storage.googleapis.com/libtpu-releases/index.html
#RUN pip install torchvision==0.20.0.dev20241126+cpu torch==2.6.0.dev20241126+cpu --extra-index-url https://download.pytorch.org/whl/nightly/cpu
#RUN pip install jax==0.4.36.dev20241122 jaxlib==0.4.36.dev20241122 -f https://storage.googleapis.com/jax-releases/jax_nightly_releases.html -f https://storage.googleapis.com/jax-releases/jaxlib_nightly_releases.html
#RUN VLLM_TARGET_DEVICE="tpu" python3 setup.py develop

# Install Jax for TPU usage, fsspec for GCS access, and transformers for OLMO
RUN pip install --no-cache-dir -U jax[tpu]==0.5.1 -f https://storage.googleapis.com/jax-releases/libtpu_releases.html fsspec==2024.9.0 transformers==4.47.0

# Installing all the core dependencies
# ['draccus>=0.8.0', 'google-api-python-client~=2.0', 'ray', 'gcsfs', 'google-cloud-storage',
# 'google-cloud-storage-transfer', 's3fs', 'regex', 'requests', 'numpy', 'torch', 'braceexpand', 'deepdiff', 'tqdm',
# 'tqdm-loggable', 'toml', 'pandas', 'pyarrow', 'jax==0.4.35', 'multiprocess==0.70.16', 'levanter>=1.2.dev1163']
RUN pip install --no-cache-dir -U draccus==0.10 google-api-python-client~=2.0 gcsfs google-cloud-storage google-cloud-storage-transfer s3fs regex requests numpy torch braceexpand deepdiff tqdm tqdm-loggable toml pandas pyarrow "levanter>=1.2.dev1207" "haliax>=1.4dev330"


# NOTE: Try to keep as much "heavy" stuff as possible before this line to avoid re-installing

# (not installing pyproject.toml because it interferes with Ray's RuntimeEnv deps)
#WORKDIR /tmp/
#ADD pyproject.toml /tmp/
#RUN pip install --no-cache-dir . --extra-index-url https://download.pytorch.org/whl/cpu

# copy in the autoscaler hacks
ENV VENV_PATH=/home/ray/anaconda3/
RUN sudo mkdir /opt/abhi-ray
RUN sudo chown -R $(whoami) /opt/abhi-ray
WORKDIR /opt/abhi-ray
RUN git clone --branch abhi-2.34.0 --single-branch --depth 1 https://github.com/abhinavg4/ray.git
RUN rm -rf $VENV_PATH/lib/python3.11/site-packages/ray/autoscaler
RUN ln -s /opt/abhi-ray/ray/python/ray/autoscaler $VENV_PATH/lib/python3.11/site-packages/ray/autoscaler

# HACK until https://github.com/ray-project/ray/issues/47769 is resolved
RUN git clone https://github.com/dlwh/ray.git ~/ray --branch tpu_docker_2.34 --depth 1
RUN cp ~/ray/python/ray/autoscaler/_private/gcp/tpu_command_runner.py $VENV_PATH/lib/python3.11/site-packages/ray/autoscaler/_private/gcp/tpu_command_runner.py
RUN rm -rf ~/ray

# Add /usr/lib/x86_64-linux-gnu/ to LD_LIBRARY_PATH so that bash prefers the systems
# libtinfo.so over the conda-provided version. Using the conda-provided libtinfo.so
# outputs a noisy warning because it doesn't include version information.
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu/
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/ray/anaconda3/lib
ENV PATH=$PATH:/home/ray/anaconda3/bin

# to run docker containers, we need to be in the docker group
RUN sudo usermod -aG docker $(whoami)

WORKDIR /opt/marin
