# vllm/vllm-tpu:9dbf7a2dc1448d6657adfb2daba36be270dcebcd - 0.7.4 has some issues
# FROM vllm/vllm-tpu:e92694b6fe264a85371317295bca6643508034ef
FROM vllm/vllm-tpu:nightly

# Setup gcsfuse
# cmake, build-essential, libssl-dev, protobuf-compiler for dolma
RUN apt-get update && apt-get install lsb-release rsync docker.io cmake build-essential libssl-dev protobuf-compiler -y
RUN usermod -aG docker $(whoami)

# Install rust for dolma
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH=$HOME/.cargo/bin:$PATH

RUN export GCSFUSE_REPO=gcsfuse-`lsb_release -c -s` && echo "deb https://packages.cloud.google.com/apt $GCSFUSE_REPO main" | tee /etc/apt/sources.list.d/gcsfuse.list
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
RUN apt-get update && apt-get install fuse gcsfuse -y
RUN mkdir /opt/gcsfuse_mount
RUN chown -R $(whoami) /opt/gcsfuse_mount

# Install the Google Cloud SDK
RUN curl -sSL https://sdk.cloud.google.com > /tmp/gcl && \
    bash /tmp/gcl --install-dir=/root/gcloud --disable-prompts \
    && chown -R $(whoami) /root/gcloud

# Install core dependencies
RUN pip install --no-cache-dir draccus==0.11.5 google-api-python-client~=2.0 gcsfs google-cloud-storage google-cloud-storage-transfer regex requests braceexpand deepdiff tqdm tqdm-loggable levanter==1.2.dev1359 haliax==1.4.dev348 lm-eval https://github.com/huggingface/accelerate/archive/refs/heads/main.zip

# Need the latest accelerate due to some deprecations in the newest pytorch
# RUN pip install --no-cache-dir https://github.com/huggingface/accelerate/archive/refs/heads/main.zip

# Add /usr/lib/x86_64-linux-gnu/ to LD_LIBRARY_PATH so that bash prefers the systems
# libtinfo.so over the conda-provided version. Using the conda-provided libtinfo.so
# outputs a noisy warning because it doesn't include version information.
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu/
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/ray/anaconda3/lib
ENV PATH=$PATH:/root/gcloud/google-cloud-sdk/bin
ENV VLLM_USE_V1=1
ENV TF_CPP_MIN_LOG_LEVEL=1
ENV HF_HOME=/opt/gcsfuse_mount/huggingface-cache

WORKDIR /opt/marin
