# Copyright The Marin Authors
# SPDX-License-Identifier: Apache-2.0
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "datasets>=3.0",
#     "huggingface_hub>=0.25",
# ]
# ///
"""Upload parser-variant fixtures from disk to a HuggingFace dataset.

Run with an HF token that can push to the target repo::

    HF_TOKEN=... uv run tests/.../parser_variants/upload_test_examples.py [--repo NAME]

Reads the on-disk fixtures generated by ``generate_test_examples.py`` and
pushes them as the ``parser_variants`` config of the target HF dataset
(default ``ravwojdyla/marin-test-fixtures``). The dataset is created public
on first push so test consumers do not require an HF token to read.

After pushing, prints the new commit SHA. Paste it into the
``PARSER_VARIANTS_REVISION`` constant in the dedup conftest to pin the
revision the tests load.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

from datasets import Dataset, Features, Value

DEFAULT_REPO = "ravwojdyla/marin-test-fixtures"
CONFIG_NAME = "parser_variants"

FIXTURE_ROOT = Path(__file__).parent
PARSERS = ("trafilatura", "html2text", "readability")

FEATURES = Features(
    {
        "article_slug": Value("string"),
        "parser": Value("string"),
        "text": Value("string"),
        "source_url": Value("string"),
        "warc_filename": Value("string"),
        "warc_offset": Value("int64"),
        "warc_length": Value("int64"),
        "capture_timestamp": Value("string"),
    }
)


def collect_rows() -> list[dict]:
    rows: list[dict] = []
    for article_dir in sorted(p for p in FIXTURE_ROOT.iterdir() if p.is_dir()):
        meta_path = article_dir / "metadata.json"
        if not meta_path.exists():
            continue
        meta = json.loads(meta_path.read_text())
        for parser in PARSERS:
            txt_path = article_dir / f"{parser}.txt"
            if not txt_path.exists():
                print(f"  WARN: missing {article_dir.name}/{parser}.txt")
                continue
            rows.append(
                {
                    "article_slug": article_dir.name,
                    "parser": parser,
                    "text": txt_path.read_text(encoding="utf-8"),
                    "source_url": meta.get("source_url", ""),
                    "warc_filename": meta.get("warc_filename", ""),
                    "warc_offset": int(meta["warc_offset"]) if meta.get("warc_offset") else 0,
                    "warc_length": int(meta["warc_length"]) if meta.get("warc_length") else 0,
                    "capture_timestamp": meta.get("capture_timestamp", ""),
                }
            )
    return rows


def main() -> None:
    cli = argparse.ArgumentParser(description="Upload parser-variant fixtures to HF.")
    cli.add_argument("--repo", default=DEFAULT_REPO, help=f"target HF dataset repo (default: {DEFAULT_REPO})")
    cli.add_argument("--dry-run", action="store_true", help="collect rows and print summary, do not push")
    args = cli.parse_args()

    if not args.dry_run and not os.environ.get("HF_TOKEN"):
        print("ERROR: HF_TOKEN env var is required for non-dry-run uploads.", file=sys.stderr)
        sys.exit(2)

    rows = collect_rows()
    if not rows:
        print(f"ERROR: no fixtures found under {FIXTURE_ROOT}", file=sys.stderr)
        sys.exit(1)

    print(f"Collected {len(rows)} rows from {FIXTURE_ROOT}:")
    for r in rows:
        print(f"  {r['article_slug']}/{r['parser']}: {len(r['text'])} chars")

    if args.dry_run:
        print("\n(dry run; skipping push)")
        return

    ds = Dataset.from_list(rows, features=FEATURES)
    print(f"\nPushing to {args.repo} (config: {CONFIG_NAME})...")
    info = ds.push_to_hub(args.repo, config_name=CONFIG_NAME, split="train")
    print(f"\nDone. Commit: {info.oid}")
    print(f"      URL:    {info.commit_url}")
    print(f"\nNext: bump PARSER_VARIANTS_REVISION in the dedup conftest to:\n      {info.oid}")


if __name__ == "__main__":
    main()
