# Copyright The Marin Authors
# SPDX-License-Identifier: Apache-2.0

"""Stamp the iris revision date into built distributions.

Every wheel and sdist build goes through this hook, so `pip install`,
`uv pip install git+…`, and the PyPI release script all produce artifacts that
can report their own revision date without carrying a `.git`. The generated
`iris/_build_info.py` exists only inside the artifact: it is written to a
temporary directory and mapped in — never into the source tree or the dist
directory, so neither a checkout nor the release manifest picks up a stray copy.

Editable installs get no stamp — an editable install *is* the checkout, and
`iris.version` resolves it from git there.
"""

import re
import sys
from pathlib import Path
from tempfile import mkdtemp

from hatchling.builders.hooks.plugin.interface import BuildHookInterface

# iris.version owns the resolution rule, and the package is not installed while
# its own build runs. A checkout keeps sources under src/; an sdist flattens
# them next to this file, and a wheel can be built from either.
_ROOT = Path(__file__).parent
sys.path[:0] = [str(_ROOT / "src"), str(_ROOT)]

from iris.version import iris_tree_date  # noqa: E402

# The wheel maps src/iris onto iris/; the sdist ships the checkout layout as is.
SOURCE_PATH = "src/iris/_build_info.py"
WHEEL_PATH = "iris/_build_info.py"
_STAMP_RE = re.compile(r'^BUILD_DATE = "(?P<date>[^"]*)"', re.MULTILINE)


def _stamped_date(root: Path) -> str:
    """The date already stamped into this tree, or "" if it carries none.

    Building a wheel from an sdist has no repository to read, but the sdist was
    itself stamped — so its value is carried through rather than blanked.
    """
    stamped = root / SOURCE_PATH
    if stamped.exists():
        match = _STAMP_RE.search(stamped.read_text())
        if match:
            return match.group("date")
    return ""


class BuildInfoHook(BuildHookInterface):
    PLUGIN_NAME = "build-info"

    def initialize(self, version: str, build_data: dict) -> None:
        if self.target_name == "editable":
            return
        root = Path(self.root)
        # Not self.directory: that is the dist directory, and a stray
        # _build_info.py beside the artifacts fails the release manifest check.
        generated = Path(mkdtemp(prefix="iris-build-info-")) / "_build_info.py"
        generated.write_text(
            "# Generated by lib/iris/hatch_build.py at build time; not tracked in git.\n"
            f'BUILD_DATE = "{iris_tree_date(root) or _stamped_date(root)}"\n'
        )
        build_data["force_include"][str(generated)] = SOURCE_PATH if self.target_name == "sdist" else WHEEL_PATH
