version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.11"
  commands:
    - pip install uv
    - uv sync --group docs --package marin
    - uv run --frozen mkdocs build --strict --site-dir $READTHEDOCS_OUTPUT/html
