version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3"
  jobs:
    pre_install:
      - python -m pip install uv
      - uv pip install --system mkdocs
      - uv pip install --system mkdocs-material
      - uv pip install --system mkdocstrings[python]
      - uv pip install --system markdown-include
      - uv pip install --system mkdocs-include-markdown-plugin

mkdocs:
  configuration: mkdocs.yml
