version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.11"
  commands:
    - pip install uv
    - uv sync --package marin --frozen
    - uv pip install mkdocs mkdocs-material mkdocstrings[python] markdown-include mkdocs-include-markdown-plugin
    - uv run --frozen mkdocs build --strict --site-dir $READTHEDOCS_OUTPUT/html
