version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - pip install uv
      - uv sync --package marin
      - uv pip install mkdocs mkdocs-material mkdocstrings[python] markdown-include mkdocs-include-markdown-plugin

mkdocs:
  configuration: mkdocs.yml
