output_base_path: gs://marin-data/scratch/rohithk
experiment: quickstart
datasets:
  - doc_path: gs://marin-data/scratch/rohithk/documents/hello_world_fw/v1.0/quickstart
    attr_path: gs://marin-data/scratch/rohithk/attributes/hello_world_fw/v1.0/quickstart
    sampling_rate: 1.0
    seed: 0
  - doc_path: gs://marin-data/scratch/rohithk/documents/reddit/v0/text
    attr_path: gs://marin-data/scratch/rohithk/attributes/reddit/v0/quickstart
    sampling_rate: 1.0
    seed: 0