output_path: gs://marin-data/scratch/rohithk
experiment: experiment-3
data_cfgs:
  - path: gs://marin-data/scratch/rohithk
    dataset: reddit
    experiment: experiment-0
    labels:
      - great
    sampling_rate: 1.0
    seed: 0