output_path : gs://marin-us-central2
experiment: quickstart
data_cfgs:
  - path: gs://marin-us-central2
    dataset: hello_world_fw/v1.0
    experiment: quickstart
    labels: []
  - path: gs://marin-us-central2
    dataset: stackexchange/v2024-04-02
    experiment: md-complete
    labels:
      - hq
