#!/bin/bash

# Load cluster ports from yaml file
# You might need to install yq (https://kislyuk.github.io/yq/)
# brew install yq

if ! command -v screen &> /dev/null
then
    echo "screen could not be found. Please install it."
    exit 1
fi

if ! command -v yq &> /dev/null
then
    echo "yq could not be found. Please install it (brew install yq)."
    exit 1
fi


SCREEN_NAME="marin-cluster-monitor"

# Check if a screen session with the given name already exists
if screen -list | grep -q "$SCREEN_NAME"; then
  echo "Screen session '$SCREEN_NAME' already exists.  Please detach or kill it first."
  exit 1
fi


screen -dmS "$SCREEN_NAME"


while IFS= read -r cluster_port_pair; do
  cluster_name=$(echo "$cluster_port_pair" | awk -F ': ' '{print $1}')
  port=$(echo "$cluster_port_pair" | awk -F ': ' '{print $2}')

  screen -S "$SCREEN_NAME" -X screen -t "$cluster_name"
  # Run ray dashboard in the background (&)
  screen -S "$SCREEN_NAME" -X stuff "ray dashboard infra/cluster/${cluster_name}.yaml -p $port &\n"
  sleep 1 # give time for ray dashboard to start, before next one starts
done < <(yq -r 'to_entries | .[] | .key + ": " + .value' infra/cluster/clusters.yaml)


echo "Screen session '$SCREEN_NAME' created with Ray dashboards. Run 'screen -r $SCREEN_NAME' to connect."
