#!/bin/bash

# Load cluster ports from yaml file
# You might need to install yq (https://kislyuk.github.io/yq/)
# brew install yq

if ! command -v screen &> /dev/null
then
    echo "screen could not be found. Please install it."
    exit 1
fi

if ! command -v yq &> /dev/null
then
    echo "yq could not be found. Please install it (brew install yq)."
    exit 1
fi


while IFS= read -r cluster_port_pair; do
  cluster_name=$(echo "$cluster_port_pair" | awk -F ': ' '{print $1}')
  port=$(echo "$cluster_port_pair" | awk -F ': ' '{print $2}')

  SCREEN_NAME="${cluster_name}"
  CLUSTER_CONFIG_PATH="./infra/${cluster_name}.yaml"
  SCREEN_LOG_FILE="$HOME/.marin_screen_logs/${SCREEN_NAME}.log"


  # Check if a screen session with the given name already exists
  if screen -list | grep -q "$SCREEN_NAME"; then
    echo "Screen session '$SCREEN_NAME' already exists. Please detach or kill it first."
    continue # Skip to the next cluster
  fi

  screen -dmS "$SCREEN_NAME"

  # Try setting DISPLAY and then run ray dashboard in the background and log output to a file
  echo screen -S "$SCREEN_NAME" -X stuff "ray dashboard --port=$port $CLUSTER_CONFIG_PATH"

  echo "Screen session '$SCREEN_NAME' created for cluster '$cluster_name'. Run 'screen -r $SCREEN_NAME' to connect. See logs in ${SCREEN_LOG_FILE}"

done < <(yq -r 'to_entries | .[] | .key + \": \" + .value' infra/cluster/clusters.yaml)


echo "Finished creating screen sessions for all clusters."
