# Unique Identifier for the Head Node + Workers
cluster_name: marin-data-dlwh

# Maximum Workers (excluding Head Node)
max_workers: 1024

# List of Available Node Types
available_node_types:
  # Head Node =>> On-Demand, sets Min/Max Workers = 0 (Prevent Scheduling Tasks on Head Node)
  head_default:
    min_workers: 0
    max_workers: 0
    resources: {"CPU": 0}

    # GCP-Specific Configuration; by default, Ray will configure unspecified fields (e.g., subnets, ssh-keys)
    #   => Ref: https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert
    node_config:
      machineType: n2-standard-8

      # Create a Persistent Disk w/ 200 GBs
      disks:
        - boot: true
          autoDelete: true
          type: PERSISTENT
          initializeParams:
            diskSizeGb: 200

            # Set Source Image =>> Ubuntu 22.04 Base VM
            sourceImage: projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts

  # Worker Nodes =>> Preemptible TPU v4-8 VMs
  tpu_worker:
    min_workers: 4
    max_workers: 1024
    resources: {"CPU": 120, "TPU": 4}

    # GCP-Specific Configuration; setup for TPU V4-8 VMs (in `us-central2-b`)
    node_config:
      acceleratorType: v4-8
      runtimeVersion: tpu-ubuntu2204-base

      # [IMPORTANT] Configure all TPU Workers to be Preemptible!
      schedulingConfig:
        preemptible: true

# Configure GCP
provider:
  type: gcp
  region: us-central2
  availability_zone: us-central2-b
  project_id: hai-gcp-models

docker:
    image: "us-central2-docker.pkg.dev/hai-gcp-models/marin/marin_cluster:latest"
    container_name: "ray_docker"
    pull_before_run: true


initialization_commands:
  - yes | gcloud auth configure-docker us-central2-docker.pkg.dev
  - which docker || (curl -fsSL https://get.docker.com -o get-docker.sh; sudo sh get-docker.sh; sudo usermod -aG docker $USER; sudo systemctl restart docker -f)
  # always run this because ray doesn't run with sudo
  - sudo usermod -aG docker $USER

setup_commands:
  # set the GCP project because it's not injected by default
  - gcloud config set project hai-gcp-models
  - gcloud config set compute/region us-central2
  - gcloud config set compute/zone us-central2-b
  - mkdir $HOME/.cache/huggingface -p
  - gcloud secrets versions access latest --secret=HF_TOKEN > $HOME/.cache/huggingface/token
#setup_commands:
#  - sudo apt install docker.io
#
#worker_setup_commands:
#  - pip install -U "jax[tpu]" -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
#
## Levanter is installed on head node without Jax
#head_setup_commands:
#  - pip install levanter@git+https://github.com/stanford-crfm/levanter.git
#
# Set Head Node == `ray_head_default`
head_node_type: head_default
