# Unique Identifier for the Head Node + Workers
cluster_name: marin-data

# Maximum Workers (excluding Head Node)
max_workers: 145

# List of Available Node Types
available_node_types:
  # Head Node =>> On-Demand, sets Min/Max Workers = 0 (Prevent Scheduling Tasks on Head Node)
  head_default:
    min_workers: 0
    max_workers: 0
    resources: {"CPU": 0}

    # GCP-Specific Configuration; by default, Ray will configure unspecified fields (e.g., subnets, ssh-keys)
    #   => Ref: https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert
    node_config:
      machineType: n2-standard-8

      # Create a Persistent Disk w/ 200 GBs
      disks:
        - boot: true
          autoDelete: true
          type: PERSISTENT
          initializeParams:
            diskSizeGb: 200

            # Set Source Image =>> Ubuntu 22.04 Base VM
            sourceImage: projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts

  # Worker Nodes =>> Preemptible TPU v4-8 VMs
  tpu_worker:
    min_workers: 4
    max_workers: 145
    resources: {"CPU": 120, "TPU": 1}

    # GCP-Specific Configuration; setup for TPU V4-8 VMs (in `us-central2-b`)
    node_config:
      acceleratorType: v4-8
      runtimeVersion: tpu-ubuntu2204-base

      # [IMPORTANT] Configure all TPU Workers to be Preemptible!
      schedulingConfig:
        preemptible: true

# Configure GCP
provider:
  type: gcp
  region: us-central2
  availability_zone: us-central2-b
  project_id: hai-gcp-models


initialization_commands:
  - sudo apt-get update
  - sudo NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
  - sudo NEEDRESTART_MODE=a DEBIAN_FRONTEND=noninteractive apt-get install -y python3-pip python-is-python3 pandoc


setup_commands:
  - pip install --upgrade pip
  - >
    pip install "chardet==5.2.0"
    "cryptography"
    "datasets==2.19.0"
    "dill==0.3.8"
    "draccus @ git+https://github.com/dlwh/draccus"
    "fsspec~=2024.3"
    "gcsfs~=2024.3"
    "s3fs~=2024.3"
    "google-api-python-client==2.129.0"
    "google-cloud-storage-transfer==1.11.3"
    "html2text==2024.2.26"
    "htmlmin==0.1.12"
    "markdownify==0.12.1"
    "multiprocess==0.70.16"
    "py7zr==0.21.0"
    "ray[default]==2.22.0"
    "rbloom==1.5.0"
    "readabilipy==0.2.0"
    "readability-lxml==0.8.1"
    "regex==2024.4.16"
    "requests"
    "tensorflow==2.16.1"
    "trafilatura==1.8.1"
    "tqdm"
    "warcio==1.7.4"


# Set Head Node == `ray_head_default`
head_node_type: head_default
