# Copy this template yaml and change the input and output directory accordingly.

input_dir: "gs://marin-$REGION/documents/$EXPERIMENT/$DATASET/$VERSION/"
output_dir: "gs://marin-$REGION/attributes/$EXPERIMENT/$DATASET/$VERSION/"
model_name: "HuggingFaceFW/fineweb-edu-classifier"
attribute_name: "fineweb-edu-quality"
runtime:
  requirements_filepath: "marin/processing/quality/config/fineweb-edu-classifier/requirements.txt"
  memory_limit_gb: 16
  tpu_resources_per_task: 1
task:
  max_in_flight: 500