input_dir: "gs://marin-data/processed/fineweb/fw-v1.0/md/"
output_dir: "gs://marin-data/processed/fineweb/fw-v1.0/attributes_md/fineweb-edu-quality/"
model_name: "HuggingFaceFW/fineweb-edu-classifier"
attribute_name: "fineweb-edu-quality"
runtime:
  requirements_filepath: "marin/processing/quality/config/fineweb-edu-classifier/requirements.txt"
  memory_limit_gb: 16
  tpu_resources_per_task: 1
task:
  max_in_flight: 500