# Copyright The Marin Authors
# SPDX-License-Identifier: Apache-2.0

import importlib.util
import sys
from pathlib import Path


def load_update_external():
    spec = importlib.util.spec_from_file_location("update_external", Path("config/update-external.py"))
    if spec is None or spec.loader is None:
        raise RuntimeError("could not load config/update-external.py")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


update_external = load_update_external()


def dependency(
    project,
    commit: str,
    *,
    repository: str = "https://github.com/marin-community/example.git",
):
    return update_external.LockedDependency(
        project=project,
        repository=repository,
        version="1.2.3",
        commit=commit,
        runtime_requirements=(),
    )


def test_render_summary_lists_each_commit_in_changed_ranges() -> None:
    unchanged_project = update_external.ExternalProject("unchanged", "unchanged", "UNCHANGED")
    changed_project = update_external.ExternalProject("changed", "changed", "CHANGED")
    unchanged = dependency(unchanged_project, "a" * 40)
    previous = dependency(changed_project, "b" * 40)
    current = dependency(changed_project, "d" * 40)
    updates = (
        update_external.DependencyUpdate(
            previous=previous,
            current=current,
            commits=(
                update_external.UpstreamCommit(commit="c" * 40, subject="Add the first behavior"),
                update_external.UpstreamCommit(commit="d" * 40, subject="Fix the second behavior"),
            ),
        ),
    )

    summary = update_external.render_summary((unchanged, current), updates)

    assert (
        summary
        == """Advance Marin's isolated external runtimes to the current commits on their configured branches.

| Project | Distribution | Version | Commit |
| --- | --- | --- | --- |
| `unchanged` | `unchanged` | `1.2.3` | [`aaaaaaaaaaaa`](https://github.com/marin-community/example/commit/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa) |
| `changed` | `changed` | `1.2.3` | [`dddddddddddd`](https://github.com/marin-community/example/commit/dddddddddddddddddddddddddddddddddddddddd) |

## Upstream commits

### changed (`bbbbbbbbbbbb` → `dddddddddddd`)

- [`cccccccccccc`](https://github.com/marin-community/example/commit/cccccccccccccccccccccccccccccccccccccccc): Add the first behavior
- [`dddddddddddd`](https://github.com/marin-community/example/commit/dddddddddddddddddddddddddddddddddddddddd): Fix the second behavior

Generated by `config/update-external.py`. Review the linked upstream changes before merging.
"""
    )
