dataset_name: med_qa
path: med_qa_en_4options_source
hf_path: bigbio/med_qa
file_type: parquet
file_names:
  - train
  - test
  - validation
prompt_key: question
options_key: choices
answer_text_key: answer
subject_key: subject
output_choices: ["A", "B", "C", "D"]
output_format: decontamination
output_prefix: gs://marin-us-central2/scratch/mmlu-draccus-update/decontamination/medqa
token: env
