# Copyright The Marin Authors
# SPDX-License-Identifier: Apache-2.0

"""Generate a CuTe pointwise skeleton from adjacent-pair scalar VJPs."""

from __future__ import annotations

import hashlib
from dataclasses import dataclass

from tile_lifetime.linear_pair_map import PairMapVjpProgram
from tile_lifetime.tensor_program import ScalarExpression, ScalarExpressionKind


@dataclass(frozen=True)
class GeneratedCutePairMapVjp:
    """Importable CuTe source and its stable semantic digest."""

    source: str
    digest: str


def generate_cute_pair_map_vjp(program: PairMapVjpProgram) -> GeneratedCutePairMapVjp:
    """Emit one generic packed-pair pointwise reverse kernel.

    The generated function plugs scalar ASTs into CODA's generic elementwise
    copy skeleton. No activation or model name is visible to the skeleton.
    """
    aliases = {
        "pair.left": "left",
        "pair.right": "right",
        "cotangent": "cotangent",
    }
    left = _cute_expression(program.left, aliases)
    right = _cute_expression(program.right, aliases)
    source = f"""# Generated by tile_lifetime.cute_pair_map_codegen; do not edit.
import torch
import cutlass
import cutlass.cute as cute

from coda.core.elementwise.templates import _elementwise_op_tuned
from coda.core.ops.misc_utils import static_assert


@cute.jit
def generated_pair_vjp_op(tX: cute.Tensor, tY: cute.Tensor, tZ: cute.Tensor) -> None:
    static_assert(tX.dtype == cute.Int32)
    static_assert(tZ.dtype == cute.Int32)
    static_assert(tY.dtype in (cute.Float16, cute.BFloat16))
    dtype = tY.dtype
    tX_pair = cute.recast_tensor(tX, dtype=dtype)
    tZ_pair = cute.recast_tensor(tZ, dtype=dtype)
    for i in cutlass.range_constexpr(cute.size(tY)):
        left = tX_pair[2 * i].to(dtype=cutlass.Float32)
        right = tX_pair[2 * i + 1].to(dtype=cutlass.Float32)
        cotangent = tY[i].to(dtype=cutlass.Float32)
        dleft = {left}
        dright = {right}
        tZ_pair[2 * i] = dleft.to(dtype=dtype)
        tZ_pair[2 * i + 1] = dright.to(dtype=dtype)


def generated_pair_vjp(preactivation, cotangent, output, config=None):
    _elementwise_op_tuned(
        op=generated_pair_vjp_op,
        X=preactivation.view(dtype=torch.int32),
        Y=cotangent,
        Z=output.view(dtype=torch.int32),
        config=config,
    )
"""
    return GeneratedCutePairMapVjp(source=source, digest=hashlib.sha256(source.encode()).hexdigest())


def _cute_expression(
    expression: ScalarExpression,
    aliases: dict[str, str],
    parent_precedence: int = 0,
) -> str:
    kind = expression.kind
    if kind is ScalarExpressionKind.INPUT:
        if expression.input_name not in aliases:
            raise ValueError(f"unbound pair-Map scalar input {expression.input_name!r}")
        return aliases[expression.input_name]
    if kind is ScalarExpressionKind.CONSTANT:
        return repr(expression.constant)
    if kind in {ScalarExpressionKind.EXP, ScalarExpressionKind.RSQRT, ScalarExpressionKind.TANH}:
        function = {
            ScalarExpressionKind.EXP: "cute.exp",
            ScalarExpressionKind.RSQRT: "cute.rsqrt",
            ScalarExpressionKind.TANH: "cute.tanh",
        }[kind]
        return f"{function}({_cute_expression(expression.operands[0], aliases)})"
    if kind is ScalarExpressionKind.SELECT:
        predicate, when_true, when_false = expression.operands
        return (
            f"cute.where({_cute_expression(predicate, aliases)}, {_cute_expression(when_true, aliases)}, "
            f"{_cute_expression(when_false, aliases)})"
        )
    symbols = {
        ScalarExpressionKind.ADD: ("+", 1),
        ScalarExpressionKind.SUBTRACT: ("-", 1),
        ScalarExpressionKind.MULTIPLY: ("*", 2),
        ScalarExpressionKind.DIVIDE: ("/", 2),
        ScalarExpressionKind.LESS_EQUAL: ("<=", 0),
    }
    try:
        symbol, precedence = symbols[kind]
    except KeyError as error:
        raise ValueError(f"unsupported CuTe scalar operation {kind.value}") from error
    left = _cute_expression(expression.operands[0], aliases, precedence)
    right = _cute_expression(expression.operands[1], aliases, precedence + 1)
    rendered = f"{left} {symbol} {right}"
    return f"({rendered})" if precedence < parent_precedence else rendered
