# Copyright The Marin Authors
# SPDX-License-Identifier: Apache-2.0

"""Generate the synchronization ABI for a generic SM100 grouped Contract."""

from __future__ import annotations

from pathlib import Path

from tile_lifetime.grouped_contract_event_schedule import (
    GroupedContractPhysicalEventSchedule,
    GroupedContractReleasePoint,
    GroupedContractSynchronizationDescriptor,
    GroupedContractWorkerAssignment,
    derive_grouped_contract_physical_event_schedule,
)

SM100_BF16_GROUPED_CONTRACT_CLUSTER_CTAS = 2
SM100_BF16_GROUPED_CONTRACT_LOAD_STAGES = 6
SM100_BF16_GROUPED_CONTRACT_TILE_ROWS_PER_CTA = 128
SM100_BF16_GROUPED_CONTRACT_TILE_REDUCTION = 64
SM100_BF16_BYTES = 2


def sm100_bf16_grouped_contract_descriptor() -> GroupedContractSynchronizationDescriptor:
    """Return the generic worker/buffer contract of the selected SM100 template."""
    operand_bytes = (
        2 * SM100_BF16_GROUPED_CONTRACT_TILE_ROWS_PER_CTA * SM100_BF16_GROUPED_CONTRACT_TILE_REDUCTION * SM100_BF16_BYTES
    )
    return GroupedContractSynchronizationDescriptor(
        workers=GroupedContractWorkerAssignment(
            cluster_ctas=SM100_BF16_GROUPED_CONTRACT_CLUSTER_CTAS,
            transfer_warpgroups_per_cta=1,
            matrix_warpgroups=1,
            epilogue_warpgroups_per_cta=1,
            matrix_owner_cta=0,
        ),
        load_pipeline_stages=SM100_BF16_GROUPED_CONTRACT_LOAD_STAGES,
        operand_bytes_per_transfer_owner=operand_bytes,
        operand_release_point=GroupedContractReleasePoint.MATRIX_OPERAND_CONSUMED,
        output_release_point=GroupedContractReleasePoint.ACCUMULATOR_READ_COMPLETE,
    )


def sm100_bf16_grouped_contract_event_schedule() -> GroupedContractPhysicalEventSchedule:
    """Instantiate enough generic K work to expose every bounded-buffer edge."""
    descriptor = sm100_bf16_grouped_contract_descriptor()
    return derive_grouped_contract_physical_event_schedule(
        descriptor,
        reduction_partition_count=descriptor.load_pipeline_stages + 1,
        generation_count=2,
    )


def render_sm100_grouped_contract_event_include(schedule: GroupedContractPhysicalEventSchedule) -> str:
    """Render constants consumed by the SM100 grouped-Contract wrapper.

    Transaction completion is a physical mbarrier mode.  Its Boolean value is
    intentionally emitted separately from the logical Event Tensor counts.
    """
    descriptor = schedule.descriptor
    return "\n".join(
        (
            "// Generated by tile_lifetime.sm100_grouped_contract_event_codegen; do not edit.",
            f'#define SHUTTLE_GROUPED_CONTRACT_EVENT_SHA256 "{schedule.fingerprint}"',
            "",
            "namespace shuttle_grouped_contract_event {",
            f"inline constexpr int kClusterCtas = {descriptor.workers.cluster_ctas};",
            f"inline constexpr int kLoadPipelineStages = {descriptor.load_pipeline_stages};",
            f"inline constexpr int kOperandReadyLogicalCount = {schedule.operand_ready_count};",
            f"inline constexpr int kOperandReleaseLogicalCount = {schedule.operand_release_count};",
            f"inline constexpr int kOutputReadyLogicalCount = {schedule.output_ready_count};",
            f"inline constexpr int kOutputReleaseLogicalCount = {schedule.output_release_count};",
            f"inline constexpr int kOperandTransactionBytes = {schedule.operand_transaction_bytes};",
            "inline constexpr int kTransactionCompletionEnabled = " f"{int(schedule.transaction_completion_enabled)};",
            "}  // namespace shuttle_grouped_contract_event",
            "",
        )
    )


def verify_sm100_grouped_contract_event_include(
    path: Path,
    schedule: GroupedContractPhysicalEventSchedule,
) -> None:
    """Reject a checked-in synchronization include that drifted from its plan."""
    expected = render_sm100_grouped_contract_event_include(schedule)
    observed = path.read_text()
    if observed != expected:
        raise ValueError(
            f"generated grouped-Contract event include {path} does not match schedule {schedule.fingerprint}; "
            "regenerate it from render_sm100_grouped_contract_event_include()"
        )
