# Copyright The Marin Authors
# SPDX-License-Identifier: Apache-2.0

"""Plan typed-FFI boundaries for Contracts with partitioned output demand.

This module stops before selecting a CUDA mainloop.  The preferred candidate is
one concatenated mainloop with partition-aware operand loads and result stores;
issuing one kernel per partition remains a legal but usually inferior fallback.
Neither candidate is counted as compute ownership until downstream Map/Fold
work is attached or a real materialization is removed and measured.
"""

from __future__ import annotations

import hashlib
import json
import re
from collections import Counter
from dataclasses import dataclass
from enum import StrEnum

from tile_lifetime.plan import NumericalPolicy
from tile_lifetime.xla_hlo_recovery import (
    EntryRegionValue,
    HloComputation,
    HloInstruction,
    RecoveredDemandSlicedContract,
    parse_hlo_module_text,
    recover_aligned_demand_sliced_contracts,
)

_DIMENSIONS = re.compile(
    r"(?P<name>lhs_contracting_dims|rhs_contracting_dims|lhs_batch_dims|rhs_batch_dims)=" r"\{(?P<dims>[0-9,]*)\}"
)
_MAP_OPCODES = frozenset(
    {
        "abs",
        "add",
        "bitcast",
        "broadcast",
        "compare",
        "convert",
        "copy",
        "divide",
        "exponential",
        "maximum",
        "minimum",
        "multiply",
        "negate",
        "reshape",
        "rsqrt",
        "select",
        "subtract",
        "tanh",
        "transpose",
    }
)
_COLLECTIVE_OPCODES = frozenset(
    {
        "all-gather",
        "all-reduce",
        "all-to-all",
        "collective-broadcast",
        "collective-permute",
        "reduce-scatter",
    }
)
_PHYSICAL_TEMPLATE = "generic_multi_output_contract"
_BACKEND_REQUIREMENT = (
    "one shared-reduction mainloop with partition-aware operand loads and direct partition result stores; "
    "do not materialize the concatenated result or launch one kernel per partition"
)


class DemandSlicedContractPhysicalMode(StrEnum):
    """Legal physical realizations of one recovered Contract."""

    CONCATENATED_MAINLOOP_PARTITIONED_OUTPUT = "concatenated_mainloop_partitioned_output"
    SPLIT_MAINLOOPS_BY_DEMAND = "split_mainloops_by_demand"


@dataclass(frozen=True)
class ContractDimensionRelation:
    """Dot-general dimensions retained by the physical interface."""

    lhs_contracting: tuple[int, ...]
    rhs_contracting: tuple[int, ...]
    lhs_batch: tuple[int, ...]
    rhs_batch: tuple[int, ...]


@dataclass(frozen=True)
class ContractNumericalRequirement:
    """Finite-precision boundary required from a physical mainloop."""

    input_dtype: str
    accumulation_dtype: str
    output_dtype: str
    output_rounding: str
    policy: NumericalPolicy
    partitioning_changes_reduction_order: bool


@dataclass(frozen=True)
class PartitionMapOpportunity:
    """A local Map reachable from one or more partition outputs."""

    instruction: str
    opcode: str
    source_partitions: tuple[int, ...]


@dataclass(frozen=True)
class PartitionFoldOpportunity:
    """A Fold frontier reachable through only local Maps."""

    instruction: str
    source_partitions: tuple[int, ...]


@dataclass(frozen=True)
class PartitionConsumerFrontier:
    """A nonlocal consumer reached after zero or more local Maps."""

    instruction: str
    opcode: str
    source_partitions: tuple[int, ...]


@dataclass(frozen=True)
class DemandSlicedContractFfiFamily:
    """One static typed-FFI ABI generated by the generic physical template."""

    target: str
    semantic_digest: str
    template: str
    partitioned_operand: int
    dimensions: ContractDimensionRelation
    numerical: ContractNumericalRequirement
    input_shapes: tuple[str, ...]
    output_shapes: tuple[str, ...]
    preferred_mode: DemandSlicedContractPhysicalMode
    fallback_modes: tuple[DemandSlicedContractPhysicalMode, ...]
    backend_requirement: str


@dataclass(frozen=True)
class DemandSlicedContractFfiCall:
    """One exact entry-HLO call boundary using a generic family."""

    call_name: str
    family: DemandSlicedContractFfiFamily
    recovered: RecoveredDemandSlicedContract
    inputs: tuple[EntryRegionValue, ...]
    outputs: tuple[EntryRegionValue, ...]
    removed_instructions: tuple[str, ...]
    maps: tuple[PartitionMapOpportunity, ...]
    folds: tuple[PartitionFoldOpportunity, ...]
    frontier: tuple[PartitionConsumerFrontier, ...]

    @property
    def cross_partition_maps(self) -> tuple[PartitionMapOpportunity, ...]:
        """Return local Maps that combine more than one logical partition."""
        return tuple(opportunity for opportunity in self.maps if len(opportunity.source_partitions) > 1)


@dataclass(frozen=True)
class DemandSlicedContractFfiPlan:
    """All static families and exact call sites in one HLO module."""

    families: tuple[DemandSlicedContractFfiFamily, ...]
    calls: tuple[DemandSlicedContractFfiCall, ...]

    @property
    def target_occurrences(self) -> tuple[tuple[str, int], ...]:
        """Return deterministic target multiplicities for registration."""
        counts = Counter(call.family.target for call in self.calls)
        return tuple((family.target, counts[family.target]) for family in self.families)


@dataclass(frozen=True)
class DemandSlicedContractCallAudit:
    """Exact post-replacement ABI and consumer evidence for one call."""

    call_name: str
    target: str
    inputs: tuple[str, ...]
    outputs: tuple[str, ...]
    output_users: tuple[tuple[str, tuple[str, ...]], ...]


@dataclass(frozen=True)
class DemandSlicedContractReplacementAudit:
    """Module-level liveness and placement-boundary evidence."""

    calls: tuple[DemandSlicedContractCallAudit, ...]
    removed_contract_count: int
    removed_contract_flops: int
    target_occurrences: tuple[tuple[str, int], ...]
    collective_instructions: tuple[str, ...]
    copy_count: tuple[int, int]
    transpose_count: tuple[int, int]


@dataclass(frozen=True)
class _FfiFamilyKey:
    partitioned_operand: int
    dimensions: ContractDimensionRelation
    input_shapes: tuple[str, ...]
    output_shapes: tuple[str, ...]


def plan_demand_sliced_contract_ffi(
    hlo_text: str,
    *,
    target_prefix: str,
) -> DemandSlicedContractFfiPlan:
    """Form static typed-FFI families and exact calls from generic structure."""
    module = parse_hlo_module_text(hlo_text)
    entry = module.computation(module.entry)
    instructions = {instruction.name: instruction for instruction in entry.instructions}
    users = _users(entry)
    recovered = recover_aligned_demand_sliced_contracts(hlo_text)
    family_keys: list[_FfiFamilyKey] = []
    call_records: list[tuple[RecoveredDemandSlicedContract, tuple[EntryRegionValue, ...], _FfiFamilyKey]] = []
    for region in recovered.regions:
        inputs = _physical_inputs(region, instructions, users)
        outputs = tuple(partition.output for partition in region.partitions)
        dimensions = _contract_dimensions(instructions[region.entry_instruction])
        key = _FfiFamilyKey(
            partitioned_operand=region.concatenated_operand,
            dimensions=dimensions,
            input_shapes=tuple(value.shape for value in inputs),
            output_shapes=tuple(value.shape for value in outputs),
        )
        if key not in family_keys:
            family_keys.append(key)
        call_records.append((region, inputs, key))

    families = tuple(_ffi_family(target_prefix, index, key) for index, key in enumerate(family_keys))
    family_by_key = dict(zip(family_keys, families, strict=True))
    calls = tuple(
        _ffi_call(
            index,
            region,
            inputs,
            family_by_key[key],
            entry,
            instructions,
            users,
        )
        for index, (region, inputs, key) in enumerate(call_records)
    )
    return DemandSlicedContractFfiPlan(families=families, calls=calls)


def replace_demand_sliced_contracts_with_custom_calls(
    hlo_text: str,
    plan: DemandSlicedContractFfiPlan,
) -> str:
    """Replace concatenation/Contract/slices with exact multi-result calls.

    This transformation establishes a structurally valid typed-FFI boundary. It
    does not by itself establish an accepted physical implementation; a registered
    target must satisfy the family's partition-aware single-mainloop contract.
    """
    rewritten = hlo_text
    for call in plan.calls:
        for instruction_name in call.removed_instructions:
            if instruction_name == call.recovered.entry_instruction:
                continue
            rewritten = _remove_instruction(rewritten, instruction_name)
        rewritten = _replace_contract_instruction(rewritten, call)
    parse_hlo_module_text(rewritten)
    return rewritten


def audit_demand_sliced_contract_replacement(
    original_hlo: str,
    transformed_hlo: str,
    plan: DemandSlicedContractFfiPlan,
) -> DemandSlicedContractReplacementAudit:
    """Verify calls, layouts, users, deleted work, and external collectives."""
    original_module = parse_hlo_module_text(original_hlo)
    transformed_module = parse_hlo_module_text(transformed_hlo)
    original = original_module.computation(original_module.entry)
    transformed = transformed_module.computation(transformed_module.entry)
    transformed_by_name = {instruction.name: instruction for instruction in transformed.instructions}
    transformed_users = _users(transformed)
    calls: list[DemandSlicedContractCallAudit] = []
    for expected in plan.calls:
        actual = transformed_by_name.get(expected.call_name)
        if actual is None or actual.opcode != "custom-call":
            raise ValueError(f"missing generated demand-sliced Contract call %{expected.call_name}")
        if f'custom_call_target="{expected.family.target}"' not in actual.attributes:
            raise ValueError(f"generated call %{expected.call_name} has the wrong typed-FFI target")
        expected_inputs = tuple(value.instruction for value in expected.inputs)
        if actual.operands != expected_inputs:
            raise ValueError(f"generated call %{expected.call_name} changed its physical inputs")
        for instruction_name in expected.removed_instructions:
            if instruction_name in transformed_by_name and instruction_name not in {
                output.instruction for output in expected.outputs
            }:
                raise ValueError(f"old demand-sliced instruction %{instruction_name} remains live")
        output_users: list[tuple[str, tuple[str, ...]]] = []
        for output_index, output in enumerate(expected.outputs):
            actual_output = transformed_by_name[output.instruction]
            if actual_output.opcode != "get-tuple-element" or actual_output.operands != (expected.call_name,):
                raise ValueError(f"generated output %{output.instruction} is not extracted from the typed-FFI call")
            if f"index={output_index}" not in actual_output.attributes or actual_output.shape != output.shape:
                raise ValueError(f"generated output %{output.instruction} changed its tuple index or physical layout")
            expected_users = expected.recovered.partitions[output_index].external_users
            if transformed_users[output.instruction] != expected_users:
                raise ValueError(f"generated output %{output.instruction} changed its external users")
            output_users.append((output.instruction, transformed_users[output.instruction]))
        calls.append(
            DemandSlicedContractCallAudit(
                call_name=expected.call_name,
                target=expected.family.target,
                inputs=actual.operands,
                outputs=tuple(output.instruction for output in expected.outputs),
                output_users=tuple(output_users),
            )
        )
    original_collectives = _collectives(original)
    transformed_collectives = _collectives(transformed)
    if transformed_collectives != original_collectives:
        raise ValueError("demand-sliced Contract replacement changed an external collective")
    actual_occurrences = Counter(
        family.target
        for instruction in transformed.instructions
        for family in plan.families
        if instruction.opcode == "custom-call" and f'custom_call_target="{family.target}"' in instruction.attributes
    )
    target_occurrences = tuple((family.target, actual_occurrences[family.target]) for family in plan.families)
    if target_occurrences != plan.target_occurrences:
        raise ValueError("generated demand-sliced Contract target multiplicity changed")
    return DemandSlicedContractReplacementAudit(
        calls=tuple(calls),
        removed_contract_count=len(plan.calls),
        removed_contract_flops=sum(call.recovered.flops for call in plan.calls),
        target_occurrences=target_occurrences,
        collective_instructions=tuple(name for name, _, _ in transformed_collectives),
        copy_count=(_opcode_count(original, "copy"), _opcode_count(transformed, "copy")),
        transpose_count=(_opcode_count(original, "transpose"), _opcode_count(transformed, "transpose")),
    )


def _ffi_family(
    target_prefix: str,
    index: int,
    key: _FfiFamilyKey,
) -> DemandSlicedContractFfiFamily:
    semantic_record = {
        "template": _PHYSICAL_TEMPLATE,
        "partitioned_operand": key.partitioned_operand,
        "dimensions": {
            "lhs_contracting": key.dimensions.lhs_contracting,
            "rhs_contracting": key.dimensions.rhs_contracting,
            "lhs_batch": key.dimensions.lhs_batch,
            "rhs_batch": key.dimensions.rhs_batch,
        },
        "inputs": key.input_shapes,
        "outputs": key.output_shapes,
        "numerical": {
            "input_dtype": "bf16",
            "accumulation_dtype": "f32",
            "output_dtype": "bf16",
            "output_rounding": "round_to_nearest_even",
            "policy": NumericalPolicy.ALLOW_ROUNDING_REORDER,
            "partitioning_changes_reduction_order": False,
        },
    }
    if {_dtype(shape) for shape in (*key.input_shapes, *key.output_shapes)} != {"bf16"}:
        raise ValueError("demand-sliced Contract typed-FFI planning currently requires BF16 arrays")
    return DemandSlicedContractFfiFamily(
        target=f"{target_prefix}.{index}",
        semantic_digest=hashlib.sha256(
            json.dumps(semantic_record, sort_keys=True, separators=(",", ":")).encode()
        ).hexdigest(),
        template=_PHYSICAL_TEMPLATE,
        partitioned_operand=key.partitioned_operand,
        dimensions=key.dimensions,
        numerical=ContractNumericalRequirement(
            input_dtype="bf16",
            accumulation_dtype="f32",
            output_dtype="bf16",
            output_rounding="round_to_nearest_even",
            policy=NumericalPolicy.ALLOW_ROUNDING_REORDER,
            partitioning_changes_reduction_order=False,
        ),
        input_shapes=key.input_shapes,
        output_shapes=key.output_shapes,
        preferred_mode=DemandSlicedContractPhysicalMode.CONCATENATED_MAINLOOP_PARTITIONED_OUTPUT,
        fallback_modes=(DemandSlicedContractPhysicalMode.SPLIT_MAINLOOPS_BY_DEMAND,),
        backend_requirement=_BACKEND_REQUIREMENT,
    )


def _ffi_call(
    index: int,
    region: RecoveredDemandSlicedContract,
    inputs: tuple[EntryRegionValue, ...],
    family: DemandSlicedContractFfiFamily,
    entry: HloComputation,
    instructions: dict[str, HloInstruction],
    users: dict[str, tuple[str, ...]],
) -> DemandSlicedContractFfiCall:
    concatenation = instructions[instructions[region.entry_instruction].operands[region.concatenated_operand]]
    outputs = tuple(partition.output for partition in region.partitions)
    maps, folds, frontier = _attachment_opportunities(outputs, entry, instructions, users)
    return DemandSlicedContractFfiCall(
        call_name=f"shuttle.generated.demand_sliced_contract.{index}",
        family=family,
        recovered=region,
        inputs=inputs,
        outputs=outputs,
        removed_instructions=(
            concatenation.name,
            region.entry_instruction,
            *(output.instruction for output in outputs),
        ),
        maps=maps,
        folds=folds,
        frontier=frontier,
    )


def _physical_inputs(
    region: RecoveredDemandSlicedContract,
    instructions: dict[str, HloInstruction],
    users: dict[str, tuple[str, ...]],
) -> tuple[EntryRegionValue, ...]:
    contract = instructions[region.entry_instruction]
    concatenation_name = contract.operands[region.concatenated_operand]
    concatenation = instructions[concatenation_name]
    if concatenation.opcode != "concatenate" or users[concatenation_name] != (region.entry_instruction,):
        raise ValueError("physical concatenation is not exclusively owned by the recovered Contract")
    parts = tuple(EntryRegionValue(name, instructions[name].shape) for name in concatenation.operands)
    if tuple(value.shape for value in parts) != tuple(partition.source_shape for partition in region.partitions):
        raise ValueError("physical concatenation inputs do not match recovered logical partitions")
    other_index = 1 - region.concatenated_operand
    other_name = contract.operands[other_index]
    other = EntryRegionValue(other_name, instructions[other_name].shape)
    return (*parts, other) if region.concatenated_operand == 0 else (other, *parts)


def _attachment_opportunities(
    outputs: tuple[EntryRegionValue, ...],
    entry: HloComputation,
    instructions: dict[str, HloInstruction],
    users: dict[str, tuple[str, ...]],
) -> tuple[
    tuple[PartitionMapOpportunity, ...],
    tuple[PartitionFoldOpportunity, ...],
    tuple[PartitionConsumerFrontier, ...],
]:
    source_order = {instruction.name: index for index, instruction in enumerate(entry.instructions)}
    ancestry: dict[str, frozenset[int]] = {
        output.instruction: frozenset({index}) for index, output in enumerate(outputs)
    }
    pending = [output.instruction for output in outputs]
    maps: dict[str, frozenset[int]] = {}
    folds: dict[str, frozenset[int]] = {}
    frontier: dict[str, frozenset[int]] = {}
    while pending:
        producer = pending.pop(0)
        for user_name in users.get(producer, ()):
            user = instructions[user_name]
            source_partitions = frozenset().union(*(ancestry.get(operand, frozenset()) for operand in user.operands))
            if not source_partitions:
                continue
            if user.opcode in _MAP_OPCODES:
                old = ancestry.get(user_name, frozenset())
                combined = old | source_partitions
                maps[user_name] = combined
                if combined != old:
                    ancestry[user_name] = combined
                    pending.append(user_name)
                continue
            if user.opcode == "reduce":
                folds[user_name] = folds.get(user_name, frozenset()) | source_partitions
                continue
            frontier[user_name] = frontier.get(user_name, frozenset()) | source_partitions
    ordered_maps = tuple(
        PartitionMapOpportunity(name, instructions[name].opcode, tuple(sorted(partitions)))
        for name, partitions in sorted(maps.items(), key=lambda item: source_order[item[0]])
    )
    ordered_folds = tuple(
        PartitionFoldOpportunity(name, tuple(sorted(partitions)))
        for name, partitions in sorted(folds.items(), key=lambda item: source_order[item[0]])
    )
    ordered_frontier = tuple(
        PartitionConsumerFrontier(name, instructions[name].opcode, tuple(sorted(partitions)))
        for name, partitions in sorted(frontier.items(), key=lambda item: source_order[item[0]])
    )
    return ordered_maps, ordered_folds, ordered_frontier


def _contract_dimensions(instruction: HloInstruction) -> ContractDimensionRelation:
    dimensions = {
        match.group("name"): tuple(int(value) for value in match.group("dims").split(",") if value)
        for match in _DIMENSIONS.finditer(instruction.attributes)
    }
    return ContractDimensionRelation(
        lhs_contracting=dimensions.get("lhs_contracting_dims", ()),
        rhs_contracting=dimensions.get("rhs_contracting_dims", ()),
        lhs_batch=dimensions.get("lhs_batch_dims", ()),
        rhs_batch=dimensions.get("rhs_batch_dims", ()),
    )


def _replace_contract_instruction(hlo_text: str, call: DemandSlicedContractFfiCall) -> str:
    pattern = re.compile(
        rf"^(?P<indent>\s*)%?{re.escape(call.recovered.entry_instruction)} = .*?$",
        re.MULTILINE,
    )
    matches = tuple(pattern.finditer(hlo_text))
    if len(matches) != 1:
        raise ValueError(f"expected one physical Contract %{call.recovered.entry_instruction}")
    match = matches[0]
    indent = match.group("indent")
    output_shapes = ", ".join(output.shape for output in call.outputs)
    operands = ", ".join(f"%{value.instruction}" for value in call.inputs)
    constraints = ", ".join(value.shape for value in call.inputs)
    lines = [
        f"{indent}%{call.call_name} = ({output_shapes}) custom-call({operands}), "
        f'custom_call_target="{call.family.target}", operand_layout_constraints={{{constraints}}}, '
        "api_version=API_VERSION_TYPED_FFI, backend_config={}",
        *(
            f"{indent}%{output.instruction} = {output.shape} get-tuple-element(%{call.call_name}), index={index}"
            for index, output in enumerate(call.outputs)
        ),
    ]
    return hlo_text[: match.start()] + "\n".join(lines) + hlo_text[match.end() :]


def _remove_instruction(hlo_text: str, instruction_name: str) -> str:
    pattern = re.compile(rf"^\s*%?{re.escape(instruction_name)} = .*?\n", re.MULTILINE)
    matches = tuple(pattern.finditer(hlo_text))
    if len(matches) != 1:
        raise ValueError(f"expected one physical definition for %{instruction_name}")
    match = matches[0]
    return hlo_text[: match.start()] + hlo_text[match.end() :]


def _users(entry: HloComputation) -> dict[str, tuple[str, ...]]:
    mutable: dict[str, list[str]] = {instruction.name: [] for instruction in entry.instructions}
    for instruction in entry.instructions:
        for operand in instruction.operands:
            mutable.setdefault(operand, []).append(instruction.name)
    return {name: tuple(dict.fromkeys(values)) for name, values in mutable.items()}


def _collectives(entry: HloComputation) -> tuple[tuple[str, str, str], ...]:
    return tuple(
        (instruction.name, instruction.shape, instruction.attributes)
        for instruction in entry.instructions
        if instruction.opcode in _COLLECTIVE_OPCODES
    )


def _opcode_count(entry: HloComputation, opcode: str) -> int:
    return sum(instruction.opcode == opcode for instruction in entry.instructions)


def _dtype(shape: str) -> str:
    return shape.split("[", 1)[0]
