# Copyright The Marin Authors
# SPDX-License-Identifier: Apache-2.0

"""Generate a Torch-free typed FFI for relation-edge reverse Map/Fold stages."""

import hashlib
import json
from dataclasses import dataclass

import numpy as np

from tile_lifetime.cuda_map_fold_codegen import (
    CudaArithmeticMode,
    CudaMapFoldProgram,
    CudaScalarFunction,
    render_cuda_scalar_program_include,
)
from tile_lifetime.tensor_program import ScalarExpressionKind, scalar_binary, scalar_input


@dataclass(frozen=True)
class RelationEdgeReverseFfiPlan:
    """Static buffer domains for one payload-only relation reverse handler."""

    received_rows: int
    route_slots: int
    padded_rows: int
    features: int

    def __post_init__(self) -> None:
        if min(self.received_rows, self.route_slots, self.padded_rows, self.features) <= 0:
            raise ValueError("relation-edge reverse dimensions must be positive")
        if self.features % 2:
            raise ValueError("relation-edge reverse requires an even BF16 feature dimension")


@dataclass(frozen=True)
class GeneratedRelationEdgeReverseFfi:
    """Typed-FFI source and stable semantic identities."""

    target: str
    handler_symbol: str
    source: str
    semantic_digest: str
    source_digest: str


def relation_edge_reverse_scalar_program() -> CudaMapFoldProgram:
    """Return only the generic scalar bodies consumed by relation-edge reverse."""
    multiply = scalar_binary(
        ScalarExpressionKind.MULTIPLY,
        scalar_input("value"),
        scalar_input("weight"),
    )
    add = scalar_binary(
        ScalarExpressionKind.ADD,
        scalar_input("state"),
        scalar_input("contribution"),
    )
    return CudaMapFoldProgram(
        functions=(
            CudaScalarFunction(
                "generated_edge_cotangent_map",
                ("value", "weight"),
                multiply,
                CudaArithmeticMode.EXPLICIT_RN,
            ),
            CudaScalarFunction(
                "generated_route_weight_fold_contribution",
                ("value", "weight"),
                multiply,
                CudaArithmeticMode.EXPLICIT_RN,
            ),
            CudaScalarFunction(
                "generated_route_weight_fold_update",
                ("state", "contribution"),
                add,
                CudaArithmeticMode.EXPLICIT_RN,
            ),
        )
    )


def generate_cuda_relation_edge_reverse_ffi(
    plan: RelationEdgeReverseFfiPlan,
    *,
    target: str,
) -> GeneratedRelationEdgeReverseFfi:
    """Generate edge weighting and feature reduction from generic Map/Fold ASTs."""
    program = relation_edge_reverse_scalar_program()
    functions = {function.symbol: function for function in program.functions}
    scalar_source = "\n\n".join(_render_device_function(function) for function in program.functions)
    target_symbol = target.replace(".", "_")
    semantic_record = {
        "received_rows": plan.received_rows,
        "route_slots": plan.route_slots,
        "padded_rows": plan.padded_rows,
        "features": plan.features,
        "scalar_program": program.fingerprint,
        "transport_semantics": "payload_permutation_only",
        "fold_order": "feature ascending, explicit FP32 round-to-nearest",
    }
    semantic_digest = hashlib.sha256(json.dumps(semantic_record, sort_keys=True).encode()).hexdigest()
    source = f"""// Generated by tile_lifetime.xla_relation_edge_reverse_ffi; do not edit.
#include <cstdint>
#include <string>

#include <cuda_bf16.h>
#include <cuda_runtime_api.h>

#include "xla/ffi/api/ffi.h"

namespace ffi = xla::ffi;

namespace {{
constexpr int kReceivedRows = {plan.received_rows};
constexpr int kRouteSlots = {plan.route_slots};
constexpr int kPaddedRows = {plan.padded_rows};
constexpr int kFeatures = {plan.features};

__device__ __forceinline__ float shuttle_bf16_to_f32(std::uint16_t value) {{
  return __uint_as_float(static_cast<std::uint32_t>(value) << 16);
}}

__device__ __forceinline__ std::uint16_t shuttle_f32_to_bf16(float value) {{
  union ShuttleBf16Bits {{
    __nv_bfloat16 value;
    std::uint16_t bits;
  }} converted;
  converted.value = __float2bfloat16_rn(value);
  return converted.bits;
}}

{scalar_source}

__global__ void ShuttleRelationEdgeMap(
    const std::uint16_t* received_cotangent,
    const std::int32_t* route_padded_rows,
    const float* route_weights,
    std::uint16_t* padded_cotangent) {{
  const int edge_feature = blockIdx.x * blockDim.x + threadIdx.x;
  if (edge_feature >= kReceivedRows * kRouteSlots * kFeatures) {{
    return;
  }}
  const int feature = edge_feature % kFeatures;
  const int edge = edge_feature / kFeatures;
  const int received_row = edge / kRouteSlots;
  const int padded_row = route_padded_rows[edge];
  if (padded_row < 0) {{
    return;
  }}
  const float value = shuttle_bf16_to_f32(received_cotangent[received_row * kFeatures + feature]);
  padded_cotangent[padded_row * kFeatures + feature] = shuttle_f32_to_bf16(
      {functions["generated_edge_cotangent_map"].symbol}(value, route_weights[edge]));
}}

__global__ void ShuttleRelationFeatureFold(
    const std::uint16_t* saved_edge_output,
    const std::uint16_t* received_cotangent,
    const std::int32_t* route_padded_rows,
    float* route_weight_cotangent) {{
  const int edge = blockIdx.x * blockDim.x + threadIdx.x;
  if (edge >= kReceivedRows * kRouteSlots) {{
    return;
  }}
  const int received_row = edge / kRouteSlots;
  const int padded_row = route_padded_rows[edge];
  float state = 0.0f;
  if (padded_row >= 0) {{
    for (int feature = 0; feature < kFeatures; ++feature) {{
      const float value = shuttle_bf16_to_f32(saved_edge_output[padded_row * kFeatures + feature]);
      const float cotangent = shuttle_bf16_to_f32(received_cotangent[received_row * kFeatures + feature]);
      const float contribution = {functions["generated_route_weight_fold_contribution"].symbol}(
          value, cotangent);
      state = {functions["generated_route_weight_fold_update"].symbol}(state, contribution);
    }}
  }}
  route_weight_cotangent[edge] = state;
}}

ffi::Error ShuttleRelationEdgeReverse(
    cudaStream_t stream,
    ffi::Buffer<ffi::BF16, 2> received_cotangent_buffer,
    ffi::Buffer<ffi::S32, 2> route_padded_rows_buffer,
    ffi::Buffer<ffi::F32, 2> route_weights_buffer,
    ffi::Buffer<ffi::BF16, 2> saved_edge_output_buffer,
    ffi::Result<ffi::Buffer<ffi::BF16, 2>> padded_cotangent_buffer,
    ffi::Result<ffi::Buffer<ffi::F32, 2>> route_weight_cotangent_buffer) {{
  const auto* received_cotangent =
      reinterpret_cast<const std::uint16_t*>(received_cotangent_buffer.typed_data());
  const auto* route_padded_rows = route_padded_rows_buffer.typed_data();
  const auto* route_weights = route_weights_buffer.typed_data();
  const auto* saved_edge_output =
      reinterpret_cast<const std::uint16_t*>(saved_edge_output_buffer.typed_data());
  auto* padded_cotangent =
      reinterpret_cast<std::uint16_t*>(padded_cotangent_buffer->typed_data());
  auto* route_weight_cotangent = route_weight_cotangent_buffer->typed_data();

  cudaError_t status = cudaMemsetAsync(
      padded_cotangent, 0, sizeof(std::uint16_t) * kPaddedRows * kFeatures, stream);
  if (status != cudaSuccess) {{
    return ffi::Error::Internal(std::string("relation edge memset: ") + cudaGetErrorString(status));
  }}
  constexpr int threads = 256;
  const int map_blocks = (kReceivedRows * kRouteSlots * kFeatures + threads - 1) / threads;
  ShuttleRelationEdgeMap<<<map_blocks, threads, 0, stream>>>(
      received_cotangent, route_padded_rows, route_weights, padded_cotangent);
  status = cudaGetLastError();
  if (status != cudaSuccess) {{
    return ffi::Error::Internal(std::string("relation edge Map: ") + cudaGetErrorString(status));
  }}
  const int fold_blocks = (kReceivedRows * kRouteSlots + threads - 1) / threads;
  ShuttleRelationFeatureFold<<<fold_blocks, threads, 0, stream>>>(
      saved_edge_output, received_cotangent, route_padded_rows, route_weight_cotangent);
  status = cudaGetLastError();
  if (status != cudaSuccess) {{
    return ffi::Error::Internal(std::string("relation feature Fold: ") + cudaGetErrorString(status));
  }}
  return ffi::Error::Success();
}}

auto ShuttleRelationEdgeReverseBinding() {{
  return ffi::Ffi::Bind()
      .Ctx<ffi::PlatformStream<cudaStream_t>>()
      .Arg<ffi::Buffer<ffi::BF16, 2>>()
      .Arg<ffi::Buffer<ffi::S32, 2>>()
      .Arg<ffi::Buffer<ffi::F32, 2>>()
      .Arg<ffi::Buffer<ffi::BF16, 2>>()
      .Ret<ffi::Buffer<ffi::BF16, 2>>()
      .Ret<ffi::Buffer<ffi::F32, 2>>();
}}
}}

XLA_FFI_DEFINE_HANDLER_SYMBOL(
    {target_symbol},
    ShuttleRelationEdgeReverse,
    ShuttleRelationEdgeReverseBinding());
"""
    return GeneratedRelationEdgeReverseFfi(
        target=target,
        handler_symbol=target_symbol,
        source=source,
        semantic_digest=semantic_digest,
        source_digest=hashlib.sha256(source.encode()).hexdigest(),
    )


def evaluate_relation_edge_reverse(
    plan: RelationEdgeReverseFfiPlan,
    received_cotangent: np.ndarray,
    route_padded_rows: np.ndarray,
    route_weights: np.ndarray,
    saved_edge_output: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Execute the generated edge Map and ordered feature Fold on CPU."""
    received_cotangent = np.asarray(received_cotangent, dtype=np.float32)
    route_padded_rows = np.asarray(route_padded_rows, dtype=np.int32)
    route_weights = np.asarray(route_weights, dtype=np.float32)
    saved_edge_output = np.asarray(saved_edge_output, dtype=np.float32)
    if received_cotangent.shape != (plan.received_rows, plan.features):
        raise ValueError("received cotangent shape disagrees with relation-edge plan")
    if route_padded_rows.shape != (plan.received_rows, plan.route_slots):
        raise ValueError("route row shape disagrees with relation-edge plan")
    if route_weights.shape != route_padded_rows.shape:
        raise ValueError("route weights and route rows must have identical shapes")
    if saved_edge_output.shape != (plan.padded_rows, plan.features):
        raise ValueError("saved edge output shape disagrees with relation-edge plan")
    if np.any((route_padded_rows < -1) | (route_padded_rows >= plan.padded_rows)):
        raise ValueError("route rows must be -1 or a valid padded row")
    valid_rows = route_padded_rows[route_padded_rows >= 0]
    if np.unique(valid_rows).size != valid_rows.size:
        raise ValueError("each valid relation edge must own a distinct padded row")

    padded_cotangent = np.zeros_like(saved_edge_output)
    route_weight_cotangent = np.zeros(route_padded_rows.shape, dtype=np.float32)
    for received_row in range(plan.received_rows):
        for route_slot in range(plan.route_slots):
            padded_row = int(route_padded_rows[received_row, route_slot])
            if padded_row < 0:
                continue
            weighted = received_cotangent[received_row] * route_weights[received_row, route_slot]
            padded_cotangent[padded_row] = _round_bf16(weighted)
            state = np.float32(0.0)
            for feature in range(plan.features):
                contribution = np.float32(saved_edge_output[padded_row, feature]) * np.float32(
                    received_cotangent[received_row, feature]
                )
                state = np.float32(state + np.float32(contribution))
            route_weight_cotangent[received_row, route_slot] = state
    return padded_cotangent, route_weight_cotangent


def _render_device_function(function: CudaScalarFunction) -> str:
    rendered = render_cuda_scalar_program_include(
        CudaMapFoldProgram((function,)),
        fingerprint_macro="SHUTTLE_RELATION_EDGE_SCALAR_SHA256",
        generated_by="tile_lifetime.xla_relation_edge_reverse_ffi",
    )
    return "\n".join(line for line in rendered.splitlines() if not line.startswith(("// Generated", "#define"))).strip()


def _round_bf16(value: np.ndarray) -> np.ndarray:
    bits = np.asarray(value, dtype=np.float32).view(np.uint32)
    rounded = bits + np.uint32(0x7FFF) + ((bits >> np.uint32(16)) & np.uint32(1))
    return (rounded & np.uint32(0xFFFF0000)).view(np.float32)
