# Copyright 2025 The Marin Authors
# SPDX-License-Identifier: Apache-2.0

"""Fray: Execution contexts for distributed and parallel computing.

Top-level fray exports are v2 APIs. For legacy v1 APIs, use ``fray.v1``.
"""

from fray.v2 import (
    ActorContext,
    ActorFuture,
    ActorGroup,
    ActorHandle,
    ActorMethod,
    Client,
    CpuConfig,
    DeviceConfig,
    DeviceKind,
    Entrypoint,
    EnvironmentConfig,
    GpuConfig,
    GpuType,
    JobFailed,
    JobHandle,
    JobRequest,
    JobStatus,
    LocalActorHandle,
    LocalActorMethod,
    LocalClient,
    LocalJobHandle,
    ResourceConfig,
    TpuConfig,
    TpuTopologyInfo,
    TpuType,
    create_environment,
    current_actor,
    current_client,
    get_tpu_topology,
    set_current_client,
    wait_all,
)

__all__ = [
    "ActorContext",
    "ActorFuture",
    "ActorGroup",
    "ActorHandle",
    "ActorMethod",
    "Client",
    "CpuConfig",
    "DeviceConfig",
    "DeviceKind",
    "Entrypoint",
    "EnvironmentConfig",
    "GpuConfig",
    "GpuType",
    "JobFailed",
    "JobHandle",
    "JobRequest",
    "JobStatus",
    "LocalActorHandle",
    "LocalActorMethod",
    "LocalClient",
    "LocalJobHandle",
    "ResourceConfig",
    "TpuConfig",
    "TpuTopologyInfo",
    "TpuType",
    "create_environment",
    "current_actor",
    "current_client",
    "get_tpu_topology",
    "set_current_client",
    "wait_all",
]
