model: # 1B class model
  type: llama
  seq_len: 2048
  hidden_dim: 2048
  intermediate_dim: 8192
  num_layers: 24
  num_heads: 16
  num_kv_heads: 16
  use_flash_attention: True
trainer:
  tracker:
    type: wandb
    entity: "stanford-mercury"
    project: "marin"
    tags: [ "llama", "dclm", "1B" ]
  mp: p=f32,c=bfloat16
  train_batch_size: 256  # 256 * 2048 = 524,288
  num_train_steps: 54932  # 28,800,000,000 / 524288 ~= 54,932
  steps_per_eval: 1000
  tensor_parallel_axes: [ "mlp", "heads" ]
  fsdp_axis: "embed"
  batch_axis: "batch"
optimizer:
  learning_rate: 3E-3
  weight_decay: 0.033
  min_lr_ratio: 0.1
  warmup: 5000
  cooldown: 3E-5

z_loss_weight: 1e-4
