# This is the base configuration for a "normal" levanter run.
# It is designed to run on a single dataset from scratch
data:
  tokenizer: "gpt2"
  cache_dir: "<WILL-BE-REPLACED>"
  train_urls:
    - "<WILL-BE-REPLACED>"
  validation_urls:
    - "<WILL-BE-REPLACED>"

model: # 150M class model
  type: llama
  seq_len: 4096
  use_flash_attention: True
  # ------- END OF COMMON CONFIGS -------
  hidden_dim: 768
  intermediate_dim: 2688
  num_layers: 12
  num_heads: 6
  num_kv_heads: 6

trainer:
  tracker:
    type: wandb
    project: "marin"
    tags: [ "llama", "standard_run" ]

  mp: p=f32,c=bfloat16
  train_batch_size: 256
  num_train_steps: 20000
  steps_per_eval: 1000
  tensor_parallel_axes: [ "mlp", "heads" ]
  fsdp_axis: "embed"
  batch_axis: "batch"
  checkpointer:
    save_interval: 10m
  shutdown_at_exit: true

optimizer:
  learning_rate: 4E-4
  weight_decay: 0.1
  min_lr_ratio: 0.1
  warmup: 5000
