data:
  train_urls:
    - "gs://pubmed-mosaic/openwebtext-sharded/openwebtext_train.{1..128}-of-128.jsonl.gz"
  validation_urls:
    - "gs://pubmed-mosaic/openwebtext-sharded/openwebtext_val.{1..8}-of-8.jsonl.gz"
  cache_dir: "gs://levanter-data/tokenized/openwebtext/"
  tokenizer: "gpt2"

model:
  type: llama
  hidden_dim: 768
  intermediate_dim: 2048
  num_heads: 6
  num_kv_heads: 6
  num_layers: 12
  seq_len: 1024
  gradient_checkpointing: true
trainer:
  tracker:
    project: "levanter"
    tags: [ "pile", "llama", "itest"]

  mp: p=f32,c=bfloat16
  model_axis_size: 1

  train_batch_size: 256
  num_train_steps: 20000
optimizer:
  learning_rate: 1E-3
  weight_decay: 0.1
  warmup: 0.01
