#!/usr/bin/env python3
# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
# Copyright The Marin Authors
# SPDX-License-Identifier: Apache-2.0

"""Advance isolated external projects and publish their locked Git revisions."""

import argparse
import json
import re
import subprocess
import tomllib
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).parents[1]
EXTERNAL_ROOT = Path(__file__).with_name("external")
GENERATED_PINS = ROOT / "lib" / "marin" / "src" / "marin" / "external_dependencies.py"
GIT_SUFFIX = ".git"


@dataclass(frozen=True)
class ExternalProject:
    config_name: str
    distribution: str
    constant_name: str
    runtime_distributions: tuple[str, ...] = ()

    @property
    def directory(self) -> Path:
        return EXTERNAL_ROOT / self.config_name


@dataclass(frozen=True)
class LockedDependency:
    project: ExternalProject
    repository: str
    version: str
    commit: str
    runtime_requirements: tuple[str, ...]


@dataclass(frozen=True)
class UpstreamCommit:
    commit: str
    subject: str


@dataclass(frozen=True)
class DependencyUpdate:
    previous: LockedDependency
    current: LockedDependency
    commits: tuple[UpstreamCommit, ...]


EXTERNAL_PROJECTS = (
    ExternalProject("evalchemy", "evalchemy", "EVALCHEMY"),
    ExternalProject("harbor", "harbor", "HARBOR", runtime_distributions=("daytona",)),
    ExternalProject("MarinSkyRL", "skyrl", "MARIN_SKYRL"),
)


def locked_package(lock_path: Path, distribution: str) -> dict:
    """Read one distribution record from a uv lockfile."""
    lock = tomllib.loads(lock_path.read_text())
    packages = [package for package in lock["package"] if package["name"] == distribution]
    if len(packages) != 1:
        raise ValueError(f"{lock_path}: expected one {distribution!r} package, found {len(packages)}")
    return packages[0]


def locked_git_source(lock_path: Path, distribution: str) -> tuple[str, str]:
    """Read and validate one distribution's immutable Git source."""
    package = locked_package(lock_path, distribution)
    source = package["source"]["git"]
    repository_with_query, separator, commit = source.partition("#")
    if not separator or not re.fullmatch(r"[0-9a-f]{40}", commit):
        raise ValueError(f"{lock_path}: expected a Git source ending in a full commit, found {source!r}")
    repository, _, _ = repository_with_query.partition("?")
    return repository, commit


def locked_dependency(project: ExternalProject) -> LockedDependency:
    """Read an external package and its runtime requirements from its uv lockfile."""
    lock_path = project.directory / "uv.lock"
    package = locked_package(lock_path, project.distribution)
    repository, commit = locked_git_source(lock_path, project.distribution)
    requirements = tuple(
        f"{distribution}=={locked_package(lock_path, distribution)['version']}"
        for distribution in project.runtime_distributions
    )
    return LockedDependency(
        project=project,
        repository=repository,
        version=package["version"],
        commit=commit,
        runtime_requirements=requirements,
    )


def render_pins(dependencies: tuple[LockedDependency, ...]) -> str:
    """Render the packaged pin table consumed by isolated Marin runtimes."""

    def tuple_literal(values: tuple[str, ...]) -> str:
        quoted = ", ".join(f'"{value}"' for value in values)
        return f"({quoted},)" if values else "()"

    entries = "\n\n".join(
        f"{dependency.project.constant_name} = ExternalDependency(\n"
        f'    config_name="{dependency.project.config_name}",\n'
        f'    distribution="{dependency.project.distribution}",\n'
        f'    repository="{dependency.repository}",\n'
        f'    version="{dependency.version}",\n'
        f'    commit="{dependency.commit}",\n'
        f"    runtime_requirements={tuple_literal(dependency.runtime_requirements)},\n"
        f")"
        for dependency in dependencies
    )
    constants = "\n".join(f"    {dependency.project.constant_name}," for dependency in dependencies)
    return f'''# Copyright The Marin Authors
# SPDX-License-Identifier: Apache-2.0

"""External Git revisions generated by ``config/update-external.py``.

Do not edit this file directly. Each revision comes from the corresponding
``config/external/<name>/uv.lock``.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class ExternalDependency:
    """An external distribution installed from an immutable Git revision."""

    config_name: str
    distribution: str
    repository: str
    version: str
    commit: str
    runtime_requirements: tuple[str, ...]

    def requirement(self, extras: tuple[str, ...] = ()) -> str:
        """Return a PEP 508 requirement for this revision."""
        distribution = self.distribution
        if extras:
            distribution = f"{{distribution}}[{{','.join(extras)}}]"
        return f"{{distribution}} @ git+{{self.repository}}@{{self.commit}}"


{entries}

EXTERNAL_DEPENDENCIES = (
{constants}
)
'''


def github_repository_path(repository: str) -> str:
    """Return an owner/repository path from a GitHub HTTPS URL."""
    prefix = "https://github.com/"
    repository_path = repository.removesuffix(GIT_SUFFIX).removeprefix(prefix)
    if not repository.startswith(prefix) or repository_path.count("/") != 1:
        raise ValueError(f"expected a GitHub HTTPS repository, found {repository!r}")
    return repository_path


def github_commits(repository: str, base: str, head: str) -> tuple[UpstreamCommit, ...]:
    """Return every commit in a GitHub comparison, oldest first."""
    repository_path = github_repository_path(repository)
    result = subprocess.run(
        [
            "gh",
            "api",
            f"repos/{repository_path}/compare/{base}...{head}",
            "--method",
            "GET",
            "-f",
            "per_page=100",
            "--paginate",
            "--slurp",
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    pages = json.loads(result.stdout)
    if not pages or any(page["status"] != "ahead" for page in pages):
        statuses = sorted({page["status"] for page in pages})
        raise ValueError(f"{repository}: expected {base}..{head} to be ahead, found {statuses}")

    commits = tuple(
        UpstreamCommit(
            commit=commit["sha"],
            subject=commit["commit"]["message"].partition("\n")[0],
        )
        for page in pages
        for commit in page["commits"]
    )
    expected_commits = pages[0]["total_commits"]
    if len(commits) != expected_commits:
        raise ValueError(f"{repository}: expected {expected_commits} commits in {base}..{head}, found {len(commits)}")
    return commits


def dependency_updates(
    previous: tuple[LockedDependency, ...],
    current: tuple[LockedDependency, ...],
) -> tuple[DependencyUpdate, ...]:
    """Return changed dependency ranges with their upstream commits."""
    previous_by_project = {dependency.project.config_name: dependency for dependency in previous}
    updates = []
    for current_dependency in current:
        previous_dependency = previous_by_project[current_dependency.project.config_name]
        if previous_dependency.commit == current_dependency.commit:
            continue
        if previous_dependency.repository != current_dependency.repository:
            raise ValueError(
                f"{current_dependency.project.config_name}: cannot compare different repositories "
                f"{previous_dependency.repository!r} and {current_dependency.repository!r}"
            )
        updates.append(
            DependencyUpdate(
                previous=previous_dependency,
                current=current_dependency,
                commits=github_commits(
                    current_dependency.repository,
                    previous_dependency.commit,
                    current_dependency.commit,
                ),
            )
        )
    return tuple(updates)


def render_summary(
    dependencies: tuple[LockedDependency, ...],
    updates: tuple[DependencyUpdate, ...],
) -> str:
    """Render the resolved external revisions for an automated pull request."""
    rows = "\n".join(
        f"| `{dependency.project.config_name}` | `{dependency.project.distribution}` | "
        f"`{dependency.version}` | "
        f"[`{dependency.commit[:12]}`]"
        f"({dependency.repository.removesuffix(GIT_SUFFIX)}/commit/{dependency.commit}) |"
        for dependency in dependencies
    )
    update_sections = "\n\n".join(
        f"### {update.current.project.config_name} "
        f"(`{update.previous.commit[:12]}` → `{update.current.commit[:12]}`)\n\n"
        + "\n".join(
            f"- [`{commit.commit[:12]}`]"
            f"({update.current.repository.removesuffix(GIT_SUFFIX)}/commit/{commit.commit}): "
            f"{commit.subject}"
            for commit in update.commits
        )
        for update in updates
    )
    upstream_commits = f"\n\n## Upstream commits\n\n{update_sections}" if update_sections else ""
    return f"""Advance Marin's isolated external runtimes to the current commits on their configured branches.

| Project | Distribution | Version | Commit |
| --- | --- | --- | --- |
{rows}{upstream_commits}

Generated by `config/update-external.py`. Review the linked upstream changes before merging.
"""


def synchronize_file(path: Path, expected: str, *, check: bool) -> bool:
    """Write expected content unless checking; return whether it already matched."""
    matches = path.exists() and path.read_text() == expected
    if not matches and not check:
        path.write_text(expected)
    return matches


def project_by_name(name: str) -> ExternalProject:
    """Return the configured external project named by the CLI."""
    return next(project for project in EXTERNAL_PROJECTS if project.config_name == name)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Upgrade external uv locks and publish their exact Git revisions to Marin."
    )
    parser.add_argument(
        "projects",
        nargs="*",
        choices=tuple(project.config_name for project in EXTERNAL_PROJECTS),
        metavar="PROJECT",
        help="projects to advance (default: all)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated pins without updating locks or files",
    )
    parser.add_argument(
        "--summary-file",
        type=Path,
        help="write a Markdown summary of the resolved versions and revisions",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    selected = tuple(project_by_name(name) for name in args.projects) or EXTERNAL_PROJECTS
    previous_dependencies = tuple(locked_dependency(project) for project in EXTERNAL_PROJECTS)
    if not args.check:
        for project in selected:
            subprocess.run(
                [
                    "uv",
                    "lock",
                    "--project",
                    str(project.directory),
                    "--upgrade-package",
                    project.distribution,
                ],
                check=True,
            )

    dependencies = tuple(locked_dependency(project) for project in EXTERNAL_PROJECTS)
    for dependency in dependencies:
        print(
            f"resolved {dependency.project.config_name}: "
            f"{dependency.project.distribution}=={dependency.version} commit={dependency.commit}"
        )
    if args.summary_file is not None:
        updates = dependency_updates(previous_dependencies, dependencies)
        args.summary_file.write_text(render_summary(dependencies, updates))
    pins_match = synchronize_file(GENERATED_PINS, render_pins(dependencies), check=args.check)
    if args.check and not pins_match:
        raise SystemExit("external dependency pins are stale; run `uv run config/update-external.py`")


if __name__ == "__main__":
    main()
