#!/usr/bin/env python3
# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
# Copyright The Marin Authors
# SPDX-License-Identifier: Apache-2.0

"""Advance isolated external projects and publish their locked Git revisions."""

import argparse
import re
import subprocess
import tomllib
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).parents[1]
EXTERNAL_ROOT = Path(__file__).with_name("external")
GENERATED_PINS = ROOT / "lib" / "marin" / "src" / "marin" / "external_dependencies.py"
ROOT_PYPROJECT = ROOT / "pyproject.toml"
HARBOR_SOURCE_PATTERN = re.compile(
    r'^harbor = \{ git = "https://github\.com/marin-community/harbor\.git", rev = "[0-9a-f]{40}" \}$',
    re.MULTILINE,
)


@dataclass(frozen=True)
class ExternalProject:
    config_name: str
    distribution: str
    constant_name: str

    @property
    def directory(self) -> Path:
        return EXTERNAL_ROOT / self.config_name


@dataclass(frozen=True)
class LockedDependency:
    project: ExternalProject
    repository: str
    commit: str


EXTERNAL_PROJECTS = (
    ExternalProject("evalchemy", "evalchemy", "EVALCHEMY"),
    ExternalProject("harbor", "harbor", "HARBOR"),
    ExternalProject("MarinSkyRL", "skyrl", "MARIN_SKYRL"),
)
PROJECTS_BY_NAME = {project.config_name: project for project in EXTERNAL_PROJECTS}


def locked_dependency(project: ExternalProject) -> LockedDependency:
    """Read an external package's immutable Git source from its uv lockfile."""
    lock_path = project.directory / "uv.lock"
    lock = tomllib.loads(lock_path.read_text())
    package = next(package for package in lock["package"] if package["name"] == project.distribution)
    source = package["source"]["git"]
    repository_with_query, separator, commit = source.partition("#")
    if not separator or not re.fullmatch(r"[0-9a-f]{40}", commit):
        raise ValueError(f"{lock_path}: expected a Git source ending in a full commit, found {source!r}")
    repository, _, _ = repository_with_query.partition("?")
    return LockedDependency(project=project, repository=repository, commit=commit)


def render_pins(dependencies: tuple[LockedDependency, ...]) -> str:
    """Render the packaged pin table consumed by isolated Marin runtimes."""
    entries = "\n\n".join(
        f"{dependency.project.constant_name} = ExternalDependency(\n"
        f'    config_name="{dependency.project.config_name}",\n'
        f'    distribution="{dependency.project.distribution}",\n'
        f'    repository="{dependency.repository}",\n'
        f'    commit="{dependency.commit}",\n'
        f")"
        for dependency in dependencies
    )
    constants = ", ".join(dependency.project.constant_name for dependency in dependencies)
    return f'''# Copyright The Marin Authors
# SPDX-License-Identifier: Apache-2.0

"""External Git revisions generated by ``config/update-external.py``.

Do not edit this file directly. Each revision comes from the corresponding
``config/external/<name>/uv.lock``.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class ExternalDependency:
    """An external distribution installed from an immutable Git revision."""

    config_name: str
    distribution: str
    repository: str
    commit: str

    def requirement(self, extras: tuple[str, ...] = ()) -> str:
        """Return a PEP 508 requirement for this revision."""
        distribution = self.distribution
        if extras:
            distribution = f"{{distribution}}[{{','.join(extras)}}]"
        return f"{{distribution}} @ git+{{self.repository}}@{{self.commit}}"


{entries}

EXTERNAL_DEPENDENCIES = ({constants},)
'''


def synchronized_root_pyproject(harbor: LockedDependency) -> str:
    """Render the root pyproject with its Harbor source set to the external lock."""
    current = ROOT_PYPROJECT.read_text()
    replacement = f'harbor = {{ git = "{harbor.repository}", rev = "{harbor.commit}" }}'
    updated, count = HARBOR_SOURCE_PATTERN.subn(replacement, current)
    if count != 1:
        raise ValueError(f"{ROOT_PYPROJECT}: expected exactly one pinned Harbor source, found {count}")
    return updated


def synchronize_file(path: Path, expected: str, *, check: bool) -> bool:
    """Write expected content unless checking; return whether it already matched."""
    matches = path.exists() and path.read_text() == expected
    if not matches and not check:
        path.write_text(expected)
    return matches


def root_lock_matches(harbor: LockedDependency) -> bool:
    """Return whether the root workspace lock uses the external Harbor revision."""
    lock = tomllib.loads((ROOT / "uv.lock").read_text())
    package = next(package for package in lock["package"] if package["name"] == harbor.project.distribution)
    source = package["source"]["git"]
    repository_with_query, separator, commit = source.partition("#")
    repository, _, _ = repository_with_query.partition("?")
    return bool(separator) and repository == harbor.repository and commit == harbor.commit


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Upgrade external uv locks and publish their exact Git revisions to Marin."
    )
    parser.add_argument(
        "projects",
        nargs="*",
        choices=tuple(PROJECTS_BY_NAME),
        metavar="PROJECT",
        help="projects to advance (default: all)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated pins and the root Harbor source without updating locks or files",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    selected = tuple(PROJECTS_BY_NAME[name] for name in args.projects) or EXTERNAL_PROJECTS
    if not args.check:
        for project in selected:
            subprocess.run(
                [
                    "uv",
                    "lock",
                    "--project",
                    str(project.directory),
                    "--upgrade-package",
                    project.distribution,
                ],
                check=True,
            )

    dependencies = tuple(locked_dependency(project) for project in EXTERNAL_PROJECTS)
    pins_match = synchronize_file(GENERATED_PINS, render_pins(dependencies), check=args.check)
    harbor = next(dependency for dependency in dependencies if dependency.project is PROJECTS_BY_NAME["harbor"])
    root_matches = synchronize_file(
        ROOT_PYPROJECT,
        synchronized_root_pyproject(harbor),
        check=args.check,
    )
    root_lock_is_current = root_lock_matches(harbor)
    if not args.check and (not root_matches or not root_lock_is_current):
        subprocess.run(
            ["uv", "lock", "--project", str(ROOT), "--upgrade-package", harbor.project.distribution],
            check=True,
        )
        root_lock_is_current = root_lock_matches(harbor)
    if args.check and (not pins_match or not root_matches or not root_lock_is_current):
        raise SystemExit("external dependency pins are stale; run `uv run config/update-external.py`")
    if not args.check and not root_lock_is_current:
        raise SystemExit(f"{ROOT / 'uv.lock'} did not resolve the locked Harbor revision")


if __name__ == "__main__":
    main()
