FROM node:20-slim AS frontend-builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM python:3.12-slim
WORKDIR /app

COPY pyproject.toml .
COPY poetry.lock .
RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-root --without dev

COPY server.py .

ENV DEV=false

COPY --from=frontend-builder /app/build ./build

ENTRYPOINT ["python", "server.py", "--config", "conf/gcp.conf"]
