dataset_name: gpqa_diamond
path: gpqa_diamond
hf_path: Idavidrein/gpqa 
file_names:
  - train
prompt_key: Question
answer_text_key: "Correct Answer"
doc_input_format: "Question: {question}\nAnswer:"
token: env
