// Copyright The Marin Authors
// SPDX-License-Identifier: Apache-2.0

// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-build-cpu-executable-bundle '--shuttle-test-corrupt-executable=kind=slot' --shuttle-verify-cpu-executable-bundle %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=SLOT
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-build-cpu-executable-bundle '--shuttle-test-corrupt-executable=kind=stride' --shuttle-verify-cpu-executable-bundle %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=STRIDE
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-build-cpu-executable-bundle '--shuttle-test-corrupt-executable=kind=offset' --shuttle-verify-cpu-executable-bundle %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=STORAGE
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-build-cpu-executable-bundle '--shuttle-test-corrupt-executable=kind=alignment' --shuttle-verify-cpu-executable-bundle %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=STORAGE
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-build-cpu-executable-bundle '--shuttle-test-corrupt-executable=kind=address-space' --shuttle-verify-cpu-executable-bundle %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=STORAGE
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-build-cpu-executable-bundle '--shuttle-test-corrupt-executable=kind=access' --shuttle-verify-cpu-executable-bundle %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=SOURCE
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-build-cpu-executable-bundle '--shuttle-test-corrupt-executable=kind=alias' --shuttle-verify-cpu-executable-bundle %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=ALIAS
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-build-cpu-executable-bundle '--shuttle-test-corrupt-executable=kind=dependency' --shuttle-verify-cpu-executable-bundle %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=DEPENDENCY
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-build-cpu-executable-bundle '--shuttle-test-corrupt-executable=kind=predication' --shuttle-verify-cpu-executable-bundle %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=SOURCE
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-build-cpu-executable-bundle '--shuttle-test-corrupt-executable=kind=body' --shuttle-verify-cpu-executable-bundle %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=SOURCE
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-build-cpu-executable-bundle '--shuttle-test-corrupt-executable=kind=code-byte' --shuttle-verify-cpu-executable-bundle %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=DIGEST
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-build-cpu-executable-bundle '--shuttle-test-corrupt-executable=kind=code-digest' --shuttle-verify-cpu-executable-bundle %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=DIGEST
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-build-cpu-executable-bundle '--shuttle-test-corrupt-executable=kind=cross-object' --shuttle-verify-cpu-executable-bundle %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=CROSS
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-build-cpu-executable-bundle '--shuttle-test-corrupt-executable=kind=root' --shuttle-verify-cpu-executable-bundle %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=CLOSED
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-build-cpu-executable-bundle '--shuttle-test-corrupt-executable=kind=unknown-attr' --shuttle-verify-cpu-executable-bundle %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=UNKNOWN
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-test-mutate-schedule-source-plan --shuttle-build-cpu-executable-bundle %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=PLAN
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-build-cpu-executable-bundle --shuttle-test-mutate-schedule-source-plan --shuttle-verify-cpu-executable-bundle %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=PLAN
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-test-mutate-schedule-lifetime --shuttle-build-cpu-executable-bundle %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=LIFETIME
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-build-cpu-executable-bundle --shuttle-test-mutate-schedule-lifetime --shuttle-verify-cpu-executable-bundle %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=LIFETIME
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-test-reorder-schedule-tasks --shuttle-build-cpu-executable-bundle %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=TASK
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-build-cpu-executable-bundle --shuttle-test-reorder-schedule-tasks --shuttle-verify-cpu-executable-bundle %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=TASK

// SOURCE: executable bundle no longer matches Shuttle algebra and schedule
// SLOT: slot and source buffer ordinals must be contiguous
// STRIDE: required bytes and strides must encode contiguous row-major storage
// STORAGE: closed CPU ABI requires host storage, zero offset, and natural alignment
// ALIAS: closed CPU ABI forbids aliasing and reuse
// DEPENDENCY: dependencies must equal entrypoint buffer producers
// CLOSED: invalid closed CPU executable bundle
// DIGEST: code SHA-256 does not match code bytes
// CROSS: entrypoint must bind the verified device-module code object
// UNKNOWN: does not permit discardable attributes
// PLAN: target, policy, and source fingerprint must bind materialization
// LIFETIME: schedule buffer type and lifetime must equal materialization
// TASK: schedule dependencies must equal the materialization task
