// Copyright The Marin Authors
// SPDX-License-Identifier: Apache-2.0

// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-test-mutate-schedule-indexing --shuttle-verify-simt32-row-fold-schedule %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=INDEXING
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-test-mutate-schedule-axis --shuttle-verify-simt32-row-fold-schedule %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=AXIS
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-test-mutate-schedule-tile --shuttle-verify-simt32-row-fold-schedule %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=TILE
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-test-mutate-schedule-resource --shuttle-verify-simt32-row-fold-schedule %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=RESOURCE
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-test-mutate-schedule-dependency --shuttle-verify-simt32-row-fold-schedule %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=DEPENDENCY
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-test-swap-materialization-edges --shuttle-verify-simt32-row-fold-schedule %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=SOURCE
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-test-replay-schedule-source-task --shuttle-verify-simt32-row-fold-schedule %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=BINDING
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-test-mutate-schedule-type --shuttle-verify-simt32-row-fold-schedule %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=TYPE
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-test-clone-materialization-plan --shuttle-plan-simt32-row-fold-schedule %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=MULTIPLE
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-test-clone-schedule-plan --shuttle-verify-simt32-row-fold-schedule %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=MULTIPLE
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-test-add-schedule-attribute --shuttle-verify-simt32-row-fold-schedule %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=ATTRIBUTE
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-test-add-schedule-task-attribute --shuttle-verify-simt32-row-fold-schedule %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=ATTRIBUTE
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-test-mutate-schedule-target --shuttle-verify-simt32-row-fold-schedule %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=TARGET
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-test-mutate-schedule-order --shuttle-verify-simt32-row-fold-schedule %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=ORDER
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule --shuttle-test-mutate-schedule-lifetime --shuttle-verify-simt32-row-fold-schedule %S/Inputs/jax-0.10.1-bf16-row_fold_scale_81928ab3539c0f03-forward.mlir 2>&1 | FileCheck %s --check-prefix=LIFETIME
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule %S/Inputs/f32-reduce-add-axis0.mlir 2>&1 | FileCheck %s --check-prefix=BOUNDARY
// RUN: not shuttle-test-opt --shuttle-annotate-source --shuttle-form-structural-regions --shuttle-convert-stablehlo-to-algebra --shuttle-plan-row-fold-materialization --shuttle-plan-simt32-row-fold-schedule %S/Inputs/bf16-row-fold.mlir 2>&1 | FileCheck %s --check-prefix=BOUNDARY

// INDEXING: buffer indexing must equal logical tensor rank
// AXIS: row Fold schedule requires reduction axis one
// TILE: schedule geometry must equal the SIMT32 derivation
// RESOURCE: schedule geometry must equal the SIMT32 derivation
// DEPENDENCY: schedule dependencies must equal the materialization task
// SOURCE: task order and edges must equal bound algebra SSA dependencies
// BINDING: schedule source tasks must be unique structural ordinals
// TYPE: schedule buffer type and lifetime must equal materialization
// MULTIPLE: requires exactly one
// ATTRIBUTE: does not permit discardable attributes
// TARGET: schedule geometry must equal the SIMT32 derivation
// ORDER: Fold reduction order must equal bound Fold semantics
// LIFETIME: schedule buffer type and lifetime must equal materialization
// BOUNDARY: requires exactly one connected static row Fold and Map region
