# Copy this template yaml and change the input and output directory accordingly.

input_dir: "gs://marin-us-central2/documents/dclm/explainlikeimfive"
output_dir: "gs://marin-us-central2/attributes/dclm/explainlikeimfive-refinedweb"
model_name: "gs://marin-us-central2/classifiers/dclm-replication/fasttext_model_refined_web.bin"
attribute_name: "dclm-fasttext-quality"
runtime:
  requirements_filepath: "marin/processing/classification/config/dclm_fasttext_requirements.txt"
  memory_limit_gb: 12
  tpu_resources_per_task: 0
task:
  max_in_flight: 1000
