input_path: "gs://marin-us-central2/documents/hello_world_fw/v1.0/quickstart/"
output_path: "gs://marin-us-central2/documents/hello_world_fw/v1.0/quickstart_consolidate_e2e/"
max_tasks_in_flight: 1000

filters:
  - type: "dedupe"
    attribute_path: "gs://marin-us-central2/attributes/hello_world_fw/v1.0/quickstart_duplicates/"
    name: "duplicate_text"
  - type: "classify"
    attribute_path: "gs://marin-us-central2/attributes/hello_world_fw/v1.0/dclm-fasttext-quality-quickstart/"
    name: "dclm-fasttext-quality"
    label: "__label__hq"
    threshold: 0.1