input_dir: "gs://marin-us-central2/documents/hello_world_fw/v1.0/quickstart/"
output_dir: "gs://marin-us-central2/attributes/hello_world_fw/v1.0/dclm-fasttext-quality-quickstart/"
model_name: "mlfoundations/fasttext-oh-eli5"
attribute_name: "dclm-fasttext-quality"
runtime:
  requirements_filepath: "marin/processing/classification/config/dclm_fasttext_requirements.txt"
  memory_limit_gb: 12
task:
  max_in_flight: 1000
