input_path: "gs://marin-us-central2/scratch/decontamination/"
output_path: "gs://marin-us-central2/scratch/dolma_decontamination_outputs/"
max_tasks_in_flight: 1000

filters:
  - type: "dedupe"
    attribute_path: "gs://marin-us-central2/attributes/hello_world_fw/v1.0/quickstart_decontaminate_mmlu/"
    name: "duplicate_text"