# Copyright The Marin Authors
# SPDX-License-Identifier: Apache-2.0

"""External requirements generated by ``config/update-external.py``.

Do not edit this file directly. External project revisions come from their
``config/external/<name>/uv.lock`` files, the promoted GPU vLLM release comes
from ``config/external/vllm/gpu-release.toml``, and TPU serving requirements
come from the root ``uv.lock``.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class ExternalDependency:
    """An external distribution installed from an immutable Git revision."""

    config_name: str
    distribution: str
    repository: str
    version: str
    commit: str
    runtime_requirements: tuple[str, ...]

    def requirement(self, extras: tuple[str, ...] = ()) -> str:
        """Return a PEP 508 requirement for this revision."""
        distribution = self.distribution
        if extras:
            distribution = f"{distribution}[{','.join(extras)}]"
        return f"{distribution} @ git+{self.repository}@{self.commit}"


@dataclass(frozen=True)
class VllmGpuWheel:
    """One architecture-specific wheel from a promoted vLLM GPU release."""

    architecture: str
    sm_targets: tuple[str, ...]
    url: str
    sha256: str
    runtime_requirements: tuple[str, ...]


@dataclass(frozen=True)
class VllmGpuRelease:
    """Immutable artifacts and ABI for a promoted vLLM GPU release."""

    release_tag: str
    source_commit: str
    version: str
    torch_backend: str
    wheels: tuple[VllmGpuWheel, ...]


EVALCHEMY = ExternalDependency(
    config_name="evalchemy",
    distribution="evalchemy",
    repository="https://github.com/marin-community/evalchemy.git",
    version="0.1.0",
    commit="d1a1005118e5928ed02064b85f14e8854ed28e22",
    runtime_requirements=(),
)

HARBOR = ExternalDependency(
    config_name="harbor",
    distribution="harbor",
    repository="https://github.com/marin-community/harbor.git",
    version="0.8.1",
    commit="24e5e67ac93d21c1a2202d6906f6093e0a57b86c",
    runtime_requirements=("daytona==0.200.2", "gcsfs==2026.7.0", "pydantic-settings==2.14.2", "s3fs==2026.7.0"),
)

MARIN_SKYRL = ExternalDependency(
    config_name="MarinSkyRL",
    distribution="marinskyrl",
    repository="https://github.com/marin-community/MarinSkyRL.git",
    version="0.1.0",
    commit="a906145aaf2bee56e3d8062830ef463f67722ea2",
    runtime_requirements=(),
)

VLLM_GPU_RELEASE = VllmGpuRelease(
    release_tag="marin-vllm-gpu-20260805-fa50698a9a30",
    source_commit="fa50698a9a303f7282aa0e969f35717703de4911",
    version="0.0.0.dev20260805+marin.fa50698a9a30.cu129",
    torch_backend="cu129",
    wheels=(
        VllmGpuWheel(
            architecture="x86_64",
            sm_targets=("9.0",),
            url=(
                "https://github.com/marin-community/vllm/releases/download/"
                "marin-vllm-gpu-20260805-fa50698a9a30/vllm-0.0.0.dev20260805%2Bmarin.fa50698a9a30.cu129-"
                "cp38-abi3-manylinux_2_28_x86_64.whl"
            ),
            sha256="d4e5d6e19da49c0f1dd030bd14d3ab795a10b8f1185c55162ae5daf6745c98eb",
            runtime_requirements=(
                "deep-gemm @ https://github.com/marin-community/vllm/releases/download/marin-vllm-gpu-20260805-fa50698a9a30/deep_gemm-2.5.0%2B891d57b-cp312-cp312-linux_x86_64.whl#sha256=2a98b8eed0a79267533c6302aa0e72dcd598d7bb857fa2b49e8a207171109e15",
            ),
        ),
        VllmGpuWheel(
            architecture="aarch64",
            sm_targets=("10.0",),
            url=(
                "https://github.com/marin-community/vllm/releases/download/"
                "marin-vllm-gpu-20260805-fa50698a9a30/vllm-0.0.0.dev20260805%2Bmarin.fa50698a9a30.cu129-"
                "cp38-abi3-manylinux_2_28_aarch64.whl"
            ),
            sha256="a248408d444425906a0e878513c8f31a43582ddf6e82e32a1573b6c714b677f9",
            runtime_requirements=(),
        ),
    ),
)

VLLM_FORK_REQUIREMENT = "vllm @ git+https://github.com/marin-community/vllm.git@244808e7863d53ac319a22beb548afd854d48d57"
TPU_INFERENCE_FORK_REQUIREMENT = (
    "tpu-inference @ git+https://github.com/marin-community/tpu-inference.git@e8809d492d5d6c7008369919a00384eb1c4de969"
)

EXTERNAL_DEPENDENCIES = (
    EVALCHEMY,
    HARBOR,
    MARIN_SKYRL,
)
