# Copyright The Marin Authors
# SPDX-License-Identifier: Apache-2.0

"""External requirements generated by ``config/update-external.py``.

Do not edit this file directly. External project revisions come from their
``config/external/<name>/uv.lock`` files, the promoted GPU vLLM release comes
from ``config/external/vllm/gpu.toml``, and TPU serving requirements
come from the root ``uv.lock``.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class ExternalDependency:
    """An external distribution installed from an immutable Git revision."""

    config_name: str
    distribution: str
    repository: str
    version: str
    commit: str
    runtime_requirements: tuple[str, ...]

    def requirement(self, extras: tuple[str, ...] = ()) -> str:
        """Return a PEP 508 requirement for this revision."""
        distribution = self.distribution
        if extras:
            distribution = f"{distribution}[{','.join(extras)}]"
        return f"{distribution} @ git+{self.repository}@{self.commit}"


@dataclass(frozen=True)
class VllmGpuWheel:
    """One architecture-specific wheel from a promoted vLLM GPU release."""

    architecture: str
    sm_targets: tuple[str, ...]
    url: str
    sha256: str


@dataclass(frozen=True)
class VllmGpuRelease:
    """Immutable artifacts and ABI for a promoted vLLM GPU release."""

    release_tag: str
    source_commit: str
    version: str
    torch_backend: str
    wheels: tuple[VllmGpuWheel, ...]


EVALCHEMY = ExternalDependency(
    config_name="evalchemy",
    distribution="evalchemy",
    repository="https://github.com/marin-community/evalchemy.git",
    version="0.1.0",
    commit="f7c85686d4b8d1957135a7a18391c2023b670e8d",
    runtime_requirements=(),
)

HARBOR = ExternalDependency(
    config_name="harbor",
    distribution="harbor",
    repository="https://github.com/marin-community/harbor.git",
    version="0.8.1",
    commit="ce2a55949f99f2d3baa48e5b523e0703f81280c0",
    runtime_requirements=("daytona==0.200.2", "gcsfs==2026.7.0", "pydantic-settings==2.14.2", "s3fs==2026.7.0"),
)

MARIN_SKYRL = ExternalDependency(
    config_name="MarinSkyRL",
    distribution="marinskyrl",
    repository="https://github.com/marin-community/MarinSkyRL.git",
    version="0.1.0",
    commit="73ee7fe5b43a8cef40e084d56acefca6d92642b5",
    runtime_requirements=(),
)

VLLM_GPU_RELEASE = VllmGpuRelease(
    release_tag="marin-vllm-gpu-20260911-5d4d4234d0b8",
    source_commit="5d4d4234d0b87c9285070c8b353c0ba40e345e92",
    version="0.0.0.dev20260911+marin.5d4d4234d0b8.cu132",
    torch_backend="cu132",
    wheels=(
        VllmGpuWheel(
            architecture="x86_64",
            sm_targets=("9.0",),
            url=(
                "https://github.com/marin-community/vllm/releases/download/"
                "marin-vllm-gpu-20260911-5d4d4234d0b8/vllm-0.0.0.dev20260911%2Bmarin.5d4d4234d0b8.cu132-"
                "cp38-abi3-manylinux_2_28_x86_64.whl"
            ),
            sha256="4ebef607ed534dfa210dca2fef656ceb7d4d74d67f66ea6e5b537e582393c1e8",
        ),
    ),
)

VLLM_FORK_REQUIREMENT = "vllm @ git+https://github.com/marin-community/vllm.git@3d26773be1d7aa7361a542943e3ef14f023d6f3a"
TPU_INFERENCE_FORK_REQUIREMENT = (
    "tpu-inference @ git+https://github.com/marin-community/tpu-inference.git@c63712cb74eb8183999b9bec1a75a810edb4abab"
)

EXTERNAL_DEPENDENCIES = (
    EVALCHEMY,
    HARBOR,
    MARIN_SKYRL,
)
