# Copy this template yaml and change the input and output directory accordingly.

input_dir: "gs://marin-$REGION/documents/$EXPERIMENT/$DATASET/$VERSION/"
output_dir: "gs://marin-$REGION/attributes/$EXPERIMENT/$DATASET/$VERSION/"
model_name: "mlfoundations/fasttext-oh-eli5"
attribute_name: "dclm-fasttext-quality"
runtime:
  requirements_filepath: "marin/processing/quality/config/dclm_fasttext_requirements.txt"
  memory_limit_gb: 12
  tpu_resources_per_task: 0
task:
  max_in_flight: 1000