# Project-local stub for jaxtyping.
#
# jaxtyping exposes shape-annotated aliases like `Float[Array, "B H"]` whose
# runtime value performs shape-checking via string DSL parsing. We don't want
# pyrefly to resolve those shape strings (which would require parsing the DSL
# and causes `unknown-name` noise for every dim identifier), nor do we want
# every `from jaxtyping import …` to hit `missing-import`.
#
# This stub therefore provides the minimum surface actually imported across
# the codebase — each alias is just `type[Any]`-shaped, with
# `__class_getitem__` returning `Any` so `Float[Array, "B H"]` resolves to
# `Any`.
from typing import Any

class _Shaped:
    def __class_getitem__(cls, item: Any) -> Any: ...

Array = Any
ArrayLike = Any
DTypeLike = Any
PRNGKeyArray = Any
PyTree = Any
Scalar = Any

class Float(_Shaped): ...
class Int(_Shaped): ...
class Bool(_Shaped): ...
class Shaped(_Shaped): ...
class Key(_Shaped): ...
class Complex(_Shaped): ...
class UInt(_Shaped): ...
class Num(_Shaped): ...
class Real(_Shaped): ...
class Inexact(_Shaped): ...

# Concrete dtype aliases used by `haliax.haxtyping`.
class Float16(_Shaped): ...
class Float32(_Shaped): ...
class Float64(_Shaped): ...
class BFloat16(_Shaped): ...
class Int4(_Shaped): ...
class Int8(_Shaped): ...
class Int16(_Shaped): ...
class Int32(_Shaped): ...
class Int64(_Shaped): ...
class UInt4(_Shaped): ...
class UInt8(_Shaped): ...
class UInt16(_Shaped): ...
class UInt32(_Shaped): ...
class UInt64(_Shaped): ...
class Complex64(_Shaped): ...
class Complex128(_Shaped): ...
