#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

TOPOLOGY="${MUON_BENCH_TOPOLOGY:-${1:-n1}}"
STAMP="$(date -u +%Y%m%d-%H%M%S)"

export RUN_ID="${RUN_ID:-MUON-BENCH-CORRECTNESS-L4-H128-I64-E8-${TOPOLOGY}-G4-BOUNDARYCONTRACT-cw-${STAMP}}"
export MUON_BENCH_BOUNDARY_GROUP_SIZE="${MUON_BENCH_BOUNDARY_GROUP_SIZE:-4}"
export MUON_BENCH_LAYERS="${MUON_BENCH_LAYERS:-4}"
export MUON_BENCH_HIDDEN_DIM="${MUON_BENCH_HIDDEN_DIM:-128}"
export MUON_BENCH_INTERMEDIATE_DIM="${MUON_BENCH_INTERMEDIATE_DIM:-64}"
export MUON_BENCH_NUM_EXPERTS="${MUON_BENCH_NUM_EXPERTS:-8}"
export MUON_BENCH_SWEEP_MAX_GROUPED_STACK_SIZES="${MUON_BENCH_SWEEP_MAX_GROUPED_STACK_SIZES:-4}"
export MUON_BENCH_SWEEP_BACKEND_STEPS="${MUON_BENCH_SWEEP_BACKEND_STEPS:-1}"
export MUON_BENCH_DTYPE="${MUON_BENCH_DTYPE:-bf16}"
export MUON_BENCH_NS_COMPUTE_DTYPE="${MUON_BENCH_NS_COMPUTE_DTYPE:-bf16}"
export MUON_BENCH_WARMUP="${MUON_BENCH_WARMUP:-1}"
export MUON_BENCH_ITERS="${MUON_BENCH_ITERS:-2}"
export MUON_BENCH_WANDB_GROUP="${MUON_BENCH_WANDB_GROUP:-grug-moe-cw-muon-boundary-correctness}"
export MUON_BENCH_BOUNDARY_CORRECTNESS_MAX_GLOBAL_BYTES="${MUON_BENCH_BOUNDARY_CORRECTNESS_MAX_GLOBAL_BYTES:-1073741824}"

exec bash scratch/launch_muon_packed_bank_boundary_contract.sh "$TOPOLOGY"
