#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

STAMP="$(date -u +%Y%m%d-%H%M%S)"
export RUN_ID="${RUN_ID:-MUON-BENCH-D2560-L26-R2D1E8-EDITED-H3-N2-cw-${STAMP}}"
export MARIN_PREFIX="${MARIN_PREFIX:-s3://marin-na/tmp/ttl=7d}"
export KUBECONFIG="${KUBECONFIG:-$HOME/.kube/coreweave-iris-gpu}"

export MUON_BENCH_GPU_REPLICAS="${MUON_BENCH_GPU_REPLICAS:-2}"
export MUON_BENCH_LAYERS="${MUON_BENCH_LAYERS:-26}"
export MUON_BENCH_REPLICA_AXIS="${MUON_BENCH_REPLICA_AXIS:-2}"
export MUON_BENCH_DATA_AXIS="${MUON_BENCH_DATA_AXIS:-1}"
export MUON_BENCH_EXPERT_AXIS="${MUON_BENCH_EXPERT_AXIS:-8}"
export MUON_BENCH_MODEL_AXIS="${MUON_BENCH_MODEL_AXIS:-1}"
export MUON_BENCH_NS4D_GROUP_SIZE="${MUON_BENCH_NS4D_GROUP_SIZE:-2}"
export MUON_BENCH_NS4D_GROUP_AXIS="${MUON_BENCH_NS4D_GROUP_AXIS:-replica_dcn,data}"
export MUON_BENCH_KINDS="${MUON_BENCH_KINDS:-real_expert_fsdp_grouped_muonh_optimizer_update}"
export MUON_BENCH_SWEEP_BACKEND_STEPS="${MUON_BENCH_SWEEP_BACKEND_STEPS:-3}"
export MUON_BENCH_SWEEP_MAX_GROUPED_STACK_SIZES="${MUON_BENCH_SWEEP_MAX_GROUPED_STACK_SIZES:-512}"
export MUON_BENCH_DTYPE="${MUON_BENCH_DTYPE:-bf16}"
export MUON_BENCH_NS_COMPUTE_DTYPE="${MUON_BENCH_NS_COMPUTE_DTYPE:-bf16}"
export MUON_BENCH_WARMUP="${MUON_BENCH_WARMUP:-1}"
export MUON_BENCH_ITERS="${MUON_BENCH_ITERS:-3}"
export MUON_BENCH_MODE="${MUON_BENCH_MODE:-both}"
export MUON_BENCH_ENABLE_JAX_PROFILE="${MUON_BENCH_ENABLE_JAX_PROFILE:-false}"
export MUON_BENCH_ALLOW_BOUNDARY_COLLECTIVES="${MUON_BENCH_ALLOW_BOUNDARY_COLLECTIVES:-true}"
export MUON_BENCH_DISABLE_ABSTRACT_MESH="${MUON_BENCH_DISABLE_ABSTRACT_MESH:-true}"
export MUON_BENCH_WORKER_CPU="${MUON_BENCH_WORKER_CPU:-8}"
export MUON_BENCH_WORKER_RAM="${MUON_BENCH_WORKER_RAM:-256g}"

export MUON_BENCH_TRACKER="${MUON_BENCH_TRACKER:-wandb}"
export MUON_BENCH_WANDB_PROJECT="${MUON_BENCH_WANDB_PROJECT:-${WANDB_PROJECT:-marin_moe}}"
export MUON_BENCH_WANDB_GROUP="${MUON_BENCH_WANDB_GROUP:-grug-moe-cw-muon-update-bench}"

export XLA_FLAGS="${XLA_FLAGS:---xla_gpu_enable_command_buffer=}"
export XLA_PYTHON_CLIENT_MEM_FRACTION="${XLA_PYTHON_CLIENT_MEM_FRACTION:-0.90}"

echo "Launching ${RUN_ID}"
echo "W&B: ${WANDB_ENTITY:-marin-community}/${MUON_BENCH_WANDB_PROJECT}"
echo "Output prefix: ${MARIN_PREFIX}/experiments/grug-moe-cw/muon-update-bench/${RUN_ID}-*"

bash scratch/muon_update_bench_fast_loop.sh iris fullprod-r4e8-l26-h3
