#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

STAMP="$(date -u +%Y%m%d-%H%M%S)"

export RUN_ID="${RUN_ID:-MUON-BENCH-CORRECTNESS-SMALL-R4D1E8-G4-cw-${STAMP}}"
export MARIN_PREFIX="${MARIN_PREFIX:-s3://marin-na/tmp/ttl=7d}"
export KUBECONFIG="${KUBECONFIG:-$HOME/.kube/coreweave-iris-gpu}"

export MUON_BENCH_GPU_REPLICAS="${MUON_BENCH_GPU_REPLICAS:-4}"
export MUON_BENCH_LAYERS="${MUON_BENCH_LAYERS:-4}"
export MUON_BENCH_REPLICA_AXIS="${MUON_BENCH_REPLICA_AXIS:-4}"
export MUON_BENCH_DATA_AXIS="${MUON_BENCH_DATA_AXIS:-1}"
export MUON_BENCH_EXPERT_AXIS="${MUON_BENCH_EXPERT_AXIS:-8}"
export MUON_BENCH_MODEL_AXIS="${MUON_BENCH_MODEL_AXIS:-1}"
export MUON_BENCH_NS4D_GROUP_AXIS="${MUON_BENCH_NS4D_GROUP_AXIS:-replica_dcn}"
export MUON_BENCH_NS4D_GROUP_SIZE="${MUON_BENCH_NS4D_GROUP_SIZE:-4}"

export MUON_BENCH_HIDDEN_DIM="${MUON_BENCH_HIDDEN_DIM:-16}"
export MUON_BENCH_INTERMEDIATE_DIM="${MUON_BENCH_INTERMEDIATE_DIM:-8}"
export MUON_BENCH_NUM_EXPERTS="${MUON_BENCH_NUM_EXPERTS:-8}"
export MUON_BENCH_SWEEP_BACKEND_STEPS="${MUON_BENCH_SWEEP_BACKEND_STEPS:-1}"
export MUON_BENCH_SWEEP_MAX_GROUPED_STACK_SIZES="${MUON_BENCH_SWEEP_MAX_GROUPED_STACK_SIZES:-4}"

export MUON_BENCH_KINDS="${MUON_BENCH_KINDS:-expert_fsdp_grads_to_explicit_packed_grouped_bank,expert_fsdp_packed_bank_a2a_apply_boundary,expert_fsdp_packed_bank_direct_apply_boundary}"
export MUON_BENCH_DTYPE="${MUON_BENCH_DTYPE:-bf16}"
export MUON_BENCH_NS_COMPUTE_DTYPE="${MUON_BENCH_NS_COMPUTE_DTYPE:-input}"
export MUON_BENCH_WARMUP="${MUON_BENCH_WARMUP:-0}"
export MUON_BENCH_ITERS="${MUON_BENCH_ITERS:-1}"
export MUON_BENCH_MODE="${MUON_BENCH_MODE:-both}"

export MUON_BENCH_TRACKER="${MUON_BENCH_TRACKER:-wandb}"
export MUON_BENCH_WANDB="${MUON_BENCH_WANDB:-true}"
export MUON_BENCH_WANDB_PROJECT="${MUON_BENCH_WANDB_PROJECT:-${WANDB_PROJECT:-marin_moe}}"
export MUON_BENCH_WANDB_GROUP="${MUON_BENCH_WANDB_GROUP:-grug-moe-cw-muon-boundary-correctness}"
export MUON_BENCH_ENABLE_JAX_PROFILE="${MUON_BENCH_ENABLE_JAX_PROFILE:-false}"
export MUON_BENCH_WRITE_COMPILED_HLO="${MUON_BENCH_WRITE_COMPILED_HLO:-true}"
export MUON_BENCH_ALLOW_BOUNDARY_COLLECTIVES="${MUON_BENCH_ALLOW_BOUNDARY_COLLECTIVES:-true}"
export MUON_BENCH_DISABLE_ABSTRACT_MESH="${MUON_BENCH_DISABLE_ABSTRACT_MESH:-true}"
export MUON_BENCH_FORCE_BOUNDARY_CORRECTNESS="${MUON_BENCH_FORCE_BOUNDARY_CORRECTNESS:-true}"
export MUON_BENCH_BOUNDARY_CORRECTNESS_MAX_GLOBAL_BYTES="${MUON_BENCH_BOUNDARY_CORRECTNESS_MAX_GLOBAL_BYTES:-1073741824}"

export MUON_BENCH_WORKER_CPU="${MUON_BENCH_WORKER_CPU:-8}"
export MUON_BENCH_WORKER_RAM="${MUON_BENCH_WORKER_RAM:-128g}"
export XLA_PYTHON_CLIENT_MEM_FRACTION="${XLA_PYTHON_CLIENT_MEM_FRACTION:-0.80}"

echo "Launching ${RUN_ID}"
echo "Small correctness R4: replica=${MUON_BENCH_REPLICA_AXIS} data=${MUON_BENCH_DATA_AXIS} expert=${MUON_BENCH_EXPERT_AXIS} model=${MUON_BENCH_MODEL_AXIS}"
echo "Dims: layers=${MUON_BENCH_LAYERS} hidden=${MUON_BENCH_HIDDEN_DIM} intermediate=${MUON_BENCH_INTERMEDIATE_DIM} experts=${MUON_BENCH_NUM_EXPERTS}"
echo "Kinds: ${MUON_BENCH_KINDS}"
echo "Output prefix: ${MARIN_PREFIX}/experiments/grug-moe-cw/muon-update-bench/${RUN_ID}-*"

if [[ "${MUON_BENCH_DRY_RUN:-false}" == "true" ]]; then
  echo "Dry run only; not launching Iris."
  exit 0
fi

bash scratch/muon_update_bench_fast_loop.sh iris fullprod-e8-l26-h3
