#!/usr/bin/env bash
# Re-pull vendored IFBench + IFEvalG verifier files at pinned commits.
# Idempotent: re-running on a clean tree should be a no-op (the diff to
# experiments/ifbench/verifiers/ is the only signal of upstream changes).
#
# To bump a pinned SHA: edit IFBENCH_SHA / OI_SHA below, run this script,
# review diff, run the validation gate (tests/test_reference_parity.py),
# commit.

set -euo pipefail

IFBENCH_SHA="cb932e352a505306ad0115272211df14bb8f628f"   # allenai/IFBench main @ 2026-04-11
OI_SHA="881b18458b484a4e9bc2ebe7fcdfdfe0d55ddf01"        # allenai/open-instruct main @ 2026-04-24

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="${REPO_ROOT}/experiments/ifbench/verifiers"
mkdir -p "${DEST}/ifbench" "${DEST}/ifevalg"

fetch() {
  local url="$1"
  local out="$2"
  curl -sfL "${url}" -o "${out}"
  echo "  ${out}: $(wc -c < "${out}") bytes"
}

echo "Fetching allenai/IFBench@${IFBENCH_SHA:0:12}..."
for f in instructions.py instructions_registry.py instructions_util.py; do
  fetch "https://raw.githubusercontent.com/allenai/IFBench/${IFBENCH_SHA}/${f}" "${DEST}/ifbench/${f}"
done

echo "Fetching allenai/open-instruct@${OI_SHA:0:12}:open_instruct/IFEvalG/..."
for f in instructions.py instructions_registry.py instructions_util.py; do
  fetch "https://raw.githubusercontent.com/allenai/open-instruct/${OI_SHA}/open_instruct/IFEvalG/${f}" "${DEST}/ifevalg/${f}"
done

echo "Applying import rewrites..."
python3 - <<'PY'
import re, pathlib, sys
DEST = pathlib.Path("experiments/ifbench/verifiers")
rewrites = [
    ("ifbench/instructions_registry.py", r"^import instructions$",                                "from . import instructions"),
    ("ifbench/instructions.py",          r"^import instructions_util$",                           "from . import instructions_util"),
    ("ifevalg/instructions_registry.py", r"^from open_instruct\.IFEvalG import instructions$",   "from . import instructions"),
    ("ifevalg/instructions.py",          r"^from open_instruct\.IFEvalG import instructions_util$", "from . import instructions_util"),
]
for rel, pat, repl in rewrites:
    p = DEST / rel
    src = p.read_text()
    new = re.sub(pat, repl, src, count=1, flags=re.MULTILINE)
    if new == src:
        sys.exit(f"FATAL: import rewrite did not match in {rel}")
    p.write_text(new)
    print(f"  rewrote {rel}")
PY

echo "Recomputing _versions.txt..."
python3 - <<PY
import hashlib, pathlib
DEST = pathlib.Path("experiments/ifbench/verifiers")
files = [
  ("ifbench/instructions.py",          "${IFBENCH_SHA}", "allenai/IFBench"),
  ("ifbench/instructions_registry.py", "${IFBENCH_SHA}", "allenai/IFBench"),
  ("ifbench/instructions_util.py",     "${IFBENCH_SHA}", "allenai/IFBench"),
  ("ifevalg/instructions.py",          "${OI_SHA}",       "allenai/open-instruct:open_instruct/IFEvalG"),
  ("ifevalg/instructions_registry.py", "${OI_SHA}",       "allenai/open-instruct:open_instruct/IFEvalG"),
  ("ifevalg/instructions_util.py",     "${OI_SHA}",       "allenai/open-instruct:open_instruct/IFEvalG"),
]
lines = ["# Pinned upstream sources for vendored verifiers",
         "# This file is generated by tools/refresh_ifbench_verifiers.sh",
         "# Format: <file>  <upstream-sha>  <upstream-path>  sha256=<hash>",
         ""]
for path, sha, repo in files:
    digest = hashlib.sha256((DEST / path).read_bytes()).hexdigest()
    lines.append(f"{path}  {sha[:12]}  {repo}  sha256={digest}")
(DEST / "_versions.txt").write_text("\n".join(lines) + "\n")
PY

echo "Done. Diff (cd ${REPO_ROOT} && git diff experiments/ifbench/verifiers) shows any upstream change."
echo "Re-run tests/test_reference_parity.py to confirm scoring still matches upstream."
