# non-embedding: 906,037,248
# total: 1,431,373,824

type: llama
seq_len: 4096
hidden_dim: 2048
intermediate_dim: 7168
num_layers: 16
num_heads: 16
num_kv_heads: 8
use_flash_attention: True
flash_attention_block_size: 1024
