# non-embedding: 13,631,902,720
# total: 14,945,244,160

type: llama
seq_len: 4096
use_flash_attention: True
flash_attention_block_size: 1024
# ------- END OF COMMON CONFIGS -------
hidden_dim: 5120
intermediate_dim: 17920
num_layers: 40
num_heads: 32
num_kv_heads: 8
