# non-embedding: 2,726,464,000
# total: 3,383,134,720

type: llama
seq_len: 4096
use_flash_attention: True
flash_attention_block_size: 1024
# ------- END OF COMMON CONFIGS -------
hidden_dim: 2560
intermediate_dim: 8960
num_layers: 32
num_heads: 32
num_kv_heads: 8
