name: Force run experiments

on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        jax-version: [ "0.4.26" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.NEW_GCP_JSON }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U jax==0.4.31
          git clone https://github.com/stanford-crfm/levanter.git && cd levanter
          pip install .[test] "jax[cpu]==${{ matrix.jax-version }}" "jaxlib==${{ matrix.jax-version }}"
          cd ../
          pip install . --extra-index-url https://download.pytorch.org/whl/cpu
          gcloud auth configure-docker us-central2-docker.pkg.dev

      - name: Run dry runs
        run: |
          for i in `ls experiments/*.py`; do python $i --dry_run True;done
