name: Levanter - Run tests that use ray

on:
  push:
    branches:
      - main
    paths:
      - 'lib/levanter/**'
      - 'uv.lock'
      - '.github/workflows/levanter-run_ray_tests.yaml'
  pull_request:
    paths:
      - 'lib/levanter/**'
      - 'uv.lock'
      - '.github/workflows/levanter-run_ray_tests.yaml'

jobs:
  ray_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lib/levanter
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Install uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.20"
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          working-directory: lib/levanter
      - name: Set up Python
        run: uv python install
      - name: Install dependencies
        run: uv sync --package levanter --dev
      - name: Test with pytest
        run: |
          PYTHONPATH=tests:src:. uv run --package levanter pytest tests -m "ray" --durations=20

