name: Verify PR with quickstart.py

on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          git clone https://github.com/stanford-crfm/levanter.git && cd levanter
          pip install .[test]
          cd ../
          pip install . --extra-index-url https://download.pytorch.org/whl/cpu

      - name: Start Ray cluster locally
        shell: bash -l {0}
        run: |
          ray start --head

      - name: Test quickstart pipeline
        shell: bash -l {0}
        run: |
          ray job submit --working-dir . -- python experiments/quickstart-synthetic.py --commit_hash exp-${{ github.sha }}
