name: Verify PR with quickstart.py

on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        jax-version: [ "0.4.26" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U jax==0.4.31
          git clone https://github.com/stanford-crfm/levanter.git && cd levanter 
          pip install .[test] "jax[cpu]==${{ matrix.jax-version }}" "jaxlib==${{ matrix.jax-version }}"
          cd ../
          pip install . --extra-index-url https://download.pytorch.org/whl/cpu
      

      - name: Start Ray cluster locally
        run: |
          ray start --head

      - name: Test quickstart pipeline
        run: |
          ray job submit --working-dir . -- python experiments/quickstart-synthetic.py --commit_hash exp-${{ github.sha }}
