name: Sync Speedrun Static

on:
  push:
    paths:
      - 'speedrun/static/**'
      - 'experiments/speedrun/**'
    branches:
      - nikil/speedrun-modifications
      - main
  workflow_dispatch:

jobs:
  sync-static:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Marin repo (default behavior)
      - name: Checkout Marin repo
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      # Run the leaderboard generation script (but don't commit changes to Marin)
      - name: Generate leaderboard data
        run: |
          # Create temporary static directory if it doesn't exist
          mkdir -p marin/speedrun/static/data

          python marin/speedrun/create_leaderboard.py
          echo "Generated updated runs.json file"

      # Checkout the Speedrun repo into a separate directory
      - name: Checkout Speedrun repo
        uses: actions/checkout@v3
        with:
          repository: marin-community/speedrun
          token: ${{ secrets.SPEEDRUN_LEADERBOARD_PAT }}
          path: speedrun-repo
      
      - name: Sync static files
        run: |
          # marin/speedrun/static/data that we generate as a temp dir should mirror speedrun-repo/data/
          # everything else in speedrun-repo/ should be left as-is
          rm -rf speedrun-repo/data/*
          cp -r marin/speedrun/static/data/* speedrun-repo/data/
          
          # configure and commit changes
          cd speedrun-repo
          git config user.name "speedrun-leaderboard-bot"
          git config user.email "github-actions@github.com"
          git add .
          
          # only commit and push if there are actual changes
          if ! git diff --cached --quiet; then
            git commit -m "Sync updated static files from Marin"
            git push
            echo "Successfully synced static files to speedrun repository"
          else
            echo "No changes to commit"
          fi