name: Sync Speedrun Static

on:
  push:
    paths:
      - 'marin/speedrun/**'
      - 'experiments/speedrun/**'
      - '.github/workflows/update-leaderboard.yml'
    branches:
      - nikil/speedrun-modifications
      - main
  workflow_dispatch:

jobs:
  sync-static:
    runs-on: ubuntu-latest
    steps:
      # checkout the Marin repo (default behavior)
      - name: Checkout Marin repo
        uses: actions/checkout@v3

      # set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # install required dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fsspec
      
      # run the leaderboard generation script (but don't commit changes to Marin)
      - name: Generate leaderboard data
        run: |
          # Create temporary static directory if it doesn't exist
          mkdir -p marin/speedrun/static/data

          python marin/speedrun/create_leaderboard.py
          echo "Generated updated runs.json file"

      # checkout the Speedrun repo into a separate directory
      - name: Checkout Speedrun repo
        uses: actions/checkout@v3
        with:
          repository: marin-community/speedrun
          token: ${{ secrets.SPEEDRUN_LEADERBOARD_PAT }}
          path: speedrun-repo

      - name: Debug directory structure
        run: |
          echo "Current directory structure (pwd and ls -la):"
          pwd
          ls -la
          echo "Speedrun directory structure (speedrun-repo):"
          ls -la speedrun-repo/ || echo "No speedrun directory"
          echo "Marin directory structure (marin):"
          ls -la marin/ || echo "No marin directory"
      
      - name: Sync static files
        run: |
          # marin/speedrun/static/data that we generate as a temp dir should mirror speedrun-repo/data/
          # everything else in speedrun-repo/ should be left as-is
          rm -rf speedrun-repo/data/*
          cp -r marin/speedrun/static/data/* speedrun-repo/data/
          
          # configure and commit changes
          cd speedrun-repo
          git config user.name "speedrun-leaderboard-update-bot"
          git add .
          
          # only commit and push if there are actual changes
          if ! git diff --cached --quiet; then
            git commit -m "automated update- leaderboard data"
            git push
            echo "Successfully synced static leaderboard data to speedrun repository"
          else
            echo "No changes to commit"
          fi
